local AudioConst = {
	MUSIC_CITY = 1,
	MUSIC_PVE = 2,
	MUSIC_PVP = 3,
	MUSIC_FIGHT = 4,
	MUSIC_WORLDBOSS = 5,
	MUSIC_EXPLORE = 6,
	MUSIC_RUNNING = 247,--赛跑背景
	MUSIC_GUILD_WAR_MAP = 3,
	MUSIC_GUILD_WAR_BATTLE = 3,
	MUSIC_HORSE_RACE = 7,	--跳马背景
	MUSIC_BGM_ARENA = 8,
	MUSIC_LOGIN_CREATE = 9, --登录和创角界面
	MUSIC_BGM_NEW_CITY = 10, -- 新主城
	MUSIC_BGM_HUANGLIN = 13,  -- 皇陵
	MUSCI_NEW_ANSWER=272 ,  --新版答题背景音乐

	SOUND_BUTTON = 11,
	SOUND_SHA = 101,
	SOUND_FAIL = 102,
	SOUND_WIN = 103,

	SOUND_HERO_LV = 203, --武将升级
	SOUND_HERO_BREAK = 204, --武将突破

	SOUND_POPUP_REARD = 205,--恭喜获得
	SOUND_GET_ONE_REARD = 206,--恭喜获得-单个道具
	SOUND_TIP_REARD = 207,--奖励获得

	SOUND_INSTRUMENT_ADVANCE = 208, --神兵进阶
	SOUND_EQUIP_STRENGTHEN = 209, --装备强化
	SOUND_NUM = 210, --数字翻滚
	SOUND_MASTER = 211, --强化大师
	SOUND_HERO_KARMA = 212, --名将册激活
	SOUND_HERO_RECOVERY = 213, --武将回收
	SOUND_HERO_REBORN = 214, --武将重生

	SOUND_DRAW_CARD1 = 215,		--招募一次
	SOUND_DRAW_CARD10 = 216,	--招募两次
	SOUND_DRAW_SHOW_CARD = 217, 	--招募翻牌

	SOUND_DAILY_UNLOCK = 226,		--日常副本解锁

	SOUND_SAODANG = 229,			--扫荡
	SOUND_NANMAN = 230,				--南蛮入侵

	SOUND_OFFICIAL_LEVELUP = 232,--官衔晋升
	SOUND_ARENA_FIGHT = 223,--竞技场对战
	SOUND_ARENA_WIN = 224,--竞技场胜利
	SOUND_ARENA_RANK_UP = 225,--竞技场排名


	SOUND_EXPLORE_DICE = 218,
	SOUND_EXPLORE_WALK = 219,
	SOUND_EXPLORE_EVENT = 220,


	SOUND_CREATE_ROLE_MAN = 202,--男主角进场
	SOUND_CREATE_ROLE_WOMEN = 201,--女主角进场
	SOUND_CREATE_ROLE_LEVEL_UP = 231,--主角升级

	SOUND_LVBU_IN = 233,	--吕布入场
	SOUND_START_CG = 234,	--对决
	SOUND_END_CG = 236,		--胜负已分

	SOUND_NEW_FUNC_OPEN = 237, --新功能开启
	SOUND_ACTIVITY_MONEYTREE = 228,

	SOUND_ISLANG_OPEN = 235,--浮岛开启

	SOUND_AVATAR_ACTIVITY_END = 238, --转盘
	SOUND_AVATAR_ACTIVITY_RUN = 239,
	
	SOUND_RED_PACKAGE_OPEN = 240, -- 红包弹出
	SOUND_RED_PACKAGE_RECIEVE_SUCCESS = 241, -- 红包点击领取成功
	SOUND_MA_TI = 242, --马蹄声
	SOUND_SHOOT = 243, --射击声
	SOUND_STAR_BLINK = 244, --点亮星星声
	SOUND_RUNNING_COUNTDOWN = 245,--跑步倒计时
	SOUND_RUNNING_OVER = 246, --跑步撞线
	SOUND_RUNNING_STATE = 248, --跑步状态

	SOUND_CAMP_RACE_PRE_WIN = 249, --阵营竞技-预赛-胜利
	SOUND_CAMP_RACE_PRE_LOSE = 250, --阵营竞技-预赛-失败

	SOUND_HORSE_RACE_COUNT = 251,	--跳马倒计时
	SOUND_HORSE_RACE_RUN = 252,		--马蹄声
	SOUND_HORSE_RACE_GOLD = 253,	--吃金币声
	SOUND_HORSE_RACE_JUMP = 254,	--跳跃音效
	SOUND_HORSE_RACE_DIE = 255,		--死亡音效
	SOUND_HORSE_RACE_WIN = 256,		--胜利音效
	SOUND_HORSE_RACE_SUMMARY = 257,	--弹出结算框

	SOUND_SEASON_STAR_RISE	= 258, -- 无差别升星
	SOUND_SEASON_STAR_DROP	= 259, -- 无差别降星
	SOUND_SEASON_UPGRADE	= 260, -- 无差别升级
	SOUND_SEASON_DOWNGRADE  = 261, -- 无差别降级
	
	SOUND_HORSE_JUDGE = 262, --相马
	SOUND_BUTTON_START_GAME = 263, -- 开始游戏

	SOUND_LIMIT_TIANCHONG=264 ,   -- 界限突破填充宝珠
	SOUND_LIMIT_TUPO=266,   -- 界限突破按钮
	SOUND_LIMIT_YINMAN=265,   -- 界限突破宝珠满
 	
 	SOUND_HORSE_CONQUER_LOSE = 267, --关公训马失败
 	SOUND_HORSE_CONQUER_GOOD = 268, --关公训马普通
 	SOUND_HORSE_CONQUER_WIN = 269, --关公训马成功

 	SOUND_SINGLE_BGM_32 = 270, --个人竞技32强背景音
	SOUND_SINGLE_BGM_WINNER = 271, --个人竞技冠军背景音
	
	SOUND_NEW_ANSWER_WIN = 273, -- 新版答题答对音效
	SOUND_NEW_ANSWER_LOSE = 274,  -- 新版答题答错音效
	SOUND_NEW_ANSWER_KILL1 = 275, -- 新版答题杀人音效1
	SOUND_NEW_ANSWER_KILL2 = 276, -- 新版答题杀人音效2
	SOUND_NEW_ANSWER_KILL3 = 277, -- 新版答题杀人音效3

	SOUND_NEW_ANSWER_OUT1 = 278, -- 新版答题杀人者出现音效
	SOUND_NEW_ANSWER_OUT2 = 279, -- 
	SOUND_NEW_ANSWER_OUT3 = 280, -- 

	SOUND_JADE_OPEN1 = 290,  -- 新版答题答错音效
	SOUND_JADE_OPEN2 = 291, -- 
	SOUND_JADE_OPEN3 = 292, --
    SOUND_JADE_OPEN4 = 293, -- 
    
    SOUND_GACHA_GOLDEN_OPEN = 294,    -- 进入招募BGM
    SOUND_GACHA_GOLDEN_RECRUIT = 295, -- 招募
    SOUND_GACHA_GOLDEN_HERO = 296,    -- 招募到

    SOUND_BGM_CAKE_MAIN = 297, --周年庆背景音乐
    SOUND_CAKE_EGG = 298, --周年庆使用鸡蛋
    SOUND_CAKE_CREAM = 299, --周年庆使用奶油
    SOUND_CAKE_FRUIT = 300, --周年庆使用水果
    SOUND_CAKE_LVUP = 301, --周年庆蛋糕升级
}

return AudioConst
