--play_horse_player

local play_horse_player = {
    -- key
    __key_map = {
      rank = 1,    --名次-int 
      text_1 = 2,    --文本1-string 
      text_2 = 3,    --文本2-string 
      text_3 = 4,    --文本3-string 
      text_4 = 5,    --文本4-string 
    
    },
    -- data
    _data = {
        [1] = {1,"CP mewakili kekuatanku! Aku akan menjaga cintaku, kepercayaanku dan keluargaku selamanya!","Aku Juara I karena aku bisa main! Kalian Charging uang sebanyak saya juga belum tentu menang!","Siapa Menang? Kalian pergi lihat di ranking CP siapa juara I!","Maaf, kalian semua, tidak aku anggap sama sekali!",},
        [2] = {2,"mari mari mari, pasti aku juara I pada kompetisi lari hari ini!","Top 10 Ksatria, aku No.2! Hahahaha!","Aku tidak sama seperti seseorang, Aku sangat rendah diri!","Bukan aku ingin menjadi protagonis, akulah protagonis!",},
        [3] = {3,"Sudah berapa kali salah pilih! Hari ini pilih aku pasti benar!","Apa yang dibanggakan dari No.2, aku No.3 akan segera melampauimu!","Kalah perang adalah hal biasa, siapa tahu bisa bangkit kembali.","Walau menyerah tidak akan mati, tapi aku tidak akan menyerah walau mati!",},
        [4] = {4,"Pilih aku, kau pasti tidak akan menyesal!","Tiga orang pertama begitu mendominasi, aku yang keempat akan rendah hati.","Sudah dibilang Perang Tambang membosankan, kau masih saja menggali!","Cara bermain baru kapan keluar, sangat ditunggu!",},
        [5] = {5,"Ramai sekali, bagaimana kalau aku bercerita humor untuk semuanya bersenang-senang.","Setiap hari harus meningkatkan CP, adalah sikapku saat bermain game!","Orang bertalenta harus tepat memilih tempat untuk menunjukkan talentanya, pejabat baik harus tepat memilih Tuannya.","Saat kau jongkok dan berdiri, terdengar suara dari lututmu, maka kau harus hati-hati, ini membuktikan bahwa pendengaranmu normal.",},
        [6] = {6,"Benar katamu! Aku tidak akan berdiam diri.","Aku yang ranking 6 di CP, menurutku sudah sesuai harapan, Imut-imut~","Semua akan menguntungkan jika digunakan dengan baik.","Berambisi dan bangga pada diri sendiri, para bawahan serakah, Sungai Huanghe yang mengalir ke timur, nasibku tidak tahu di mana!",},
        [7] = {7,"Salah seorang tetua, kau bukanlah kulit imitasi, tapi kau benar-benar nakal!","Aku orangnya, emosian dan angkuh, bertingkah dan suka tertawa.","Aku mungkin kebanyakan makan garam, sampai keasinan memikirkanmu.","Pada saat kompetisi, Aku tidak menonton kompetisi, Aku selalu memperhatikanmu.",},
        [8] = {8,"Ada orang leluconnya terasa sangat dingin.","Aku tidak ingin kalah dari yang lain!","Yang bisa main, main kamp mana pun juga kuat; yang tidak bisa main, main kamp mana pun marah-marah.","Segera bisa lakukan Limit Break, saat itu CP semuanya akan naik satu tingkat!",},
        [9] = {9,"Menurut kalian Da Qiao atau Diao Chan yang lebih cantik?","Demi ranking ke 9, aku tiap hari berusaha meningkatkan CP!","Mereka semua bilang aku suka ngobrol, sebenarnya aku cuma ingin ngobrol denganmu.","Pertama Lu Bu, Kedua Zhao Yun, Ketiga Dian Wei, Keempat Guan Yu, Kelima Ma Chao, Keenam Zhang Fei.",},
        [10] = {10,"Bisa mencapai Top 10 Ksatria, aku sudah senang sekali!","Satu dua tiga empat lima, emas kayu air api tanah, Ranking 10 CP paling dapat diandalkan!","Yang pintar bekerja sesuai fakta, yang bodoh merebut nama kosong.","Kalian mainnya gimana sih, CP kok bisa tinggi sekali?",},
        [11] = {11,"Jadi kau bilang aku akan kalah, aku tidak mau lari kalau begitu? Tidak coba dulu aku tidak rela!","Oleh karena itu, aku akan datang… .dengan penuh usaha… memenangkan kompetisi ini!","Piala Dunia Rusia tahun 2018 : Argentina kalah pada Juara dan Runner up.","Tidak ada akhir dari semua hal di dunia, tidak ada cara untuk menghindarinya.",},
        [12] = {12,"Semangat demi kompetisi, tidak apa-apa kalau kalah!","Skill pembuat pusing dan pengurang amarah Wei Yan sangat bagus digunakan.","Siapa bisa beritahu aku, sebenarnya kamp mana lebih hebat?","Demi balas budi tidak peduli akan bahaya yang akan diterima, perilakunya dikagumi sampai generasi saat ini.",},
        [13] = {13,"Jika aku mengubah nama, kalian masih bisa kenal aku?","Adakah kompetisi lari pada masa Tiga Negara?","Saat musim semi saya tidur di rumah jerami, dan sinar matahari di luar jendela perlahan bergerak.","Tidak ada satu pun di dunia ini yang dapat diubah oleh manusia, berusaha mati-matian juga tidak bisa melawan takdir.",},
        [14] = {14,"Aku ingin menang!","Pang Tong sangatlah hebat, apa kau tahu?","Tirani Sun Ce, sangat hebat di garis belakang!","Senang bisa bertemu dan minum arak bersama, ada banyak hal tentang dunia, hanya menjadi bahan pembicaraan dan candaan orang.",},
        [15] = {15,"Ingin sekali dengan cepat memenangkan kompetisi ini!","Mengembangkan Xu Shu untuk melewati Skenario, sungguh menyenangkan!","Mau menang? Rahasianya adalah, pilihlah aku!","Diatas langit masih ada langit, menggunakan tipuan membuat orang yang menipu marah.",},
        [16] = {16,"Tunggu lama baru mulai kompetisi, lebih baik menceritakan lelucon, agar semua orang bersenang-senang.","Aku ingin menjadi orang yang beruntung! Hero Merah, Gear Merah cepat datang!","Memarahi, juga merupakan hal menarik dalam permainan.","Seseorang yang bisa hidup dengan tenang setiap hari, mengapa repot-repot mengejar tujuan besar agar bisa terkenal?",},
        [17] = {17,"Apakah ada yang mau membagikan double Angpao!","Buatlah lebih banyak Insignia Merah, aku pasti dapat mengalahkannya!","Lama memuji Kristal, hari ini boleh menukar dengan Insignia Merah!","Anak ingusan, bagaimana mendengar suara petir yang keras; orang yang sakit-sakitan, takut untuk mendengar auman harimau.",},
        [18] = {18,"Yang dapat memaafkan penipuan wanitalah yang merupakan pria sejati.","kalian banyak omong, bisakah biarkan aku kompetisi lari dengan tenang.","Ssst! Biarkan aku dengan tenang memikirkannya.","Kau sedang apa? Jawaban satu-satunya adalah : lagi ngobrol denganmu.",},
        [19] = {19,"Jika tidak kembali, kenapa tidak dilupakan; jika tidak ada jodoh, kenapa bersumpah.","Kompetisi yang normal, di larang berbicara dengan ngawur.","Aku mencintai kalian semua, syaratnya kalian biarkan aku menang!","Kau tidak dapat membedakan orang baik atau jahat adalah mata kotor, tidak bisa mambaca buku dan puisi adalah mulut kotor; tidak bisa mendengar hal baik adalah telinga kotor.",},
        [20] = {20,"Selain aku sendiri, aku tidak memperbolehkan orang menatapku!","Aku adalah orang, kau bukan aku, jadi kau bukan orang.","Siluman Pipa datang lagi mengikuti kompetisi? Pasti untung banyak dari tiket masuk!","Tidak tahu masa lalu adalah kekotoran tubuh; tidak menerima para Marquis adalah perut kotor; sering berniat merebut kekuasaan adalah hati kotor!",},
        [21] = {21,"Bagaimana baru bisa memenangkan kompetisi dengan cantik!","Pria sejati lahir di antara bumi dan langit, bagaimana bisa tetap di bawah orang untuk waktu yang lama!","Bukan naif yang mengalahkan saya, tetapi naif yang keterlaluan!","Masih belum mulai, membosankan, bagaimana kalau bersama-sama memarahi perencana!",},
        [22] = {22,"Walau harus menunggu dengan sabar … … aku ingin mencapai Top 10 Ksatria!","Hal keluarga, hal negara, hal dunia, dengan gembira main game adalah hal besar!","Kepala Leopard juga pasti akan senang!","Dari dulu pasukan arogan sering menyebabkan kekalahan, selalu meremehkan musuh akan sulit berhasil.",},
        [23] = {23,"Aku hanya ingin melakukan sesuatu sesuai dengan kepercayaanku, tidak akan pernah menyesalinya, tidak masalah sekarang atau di masa depan, akan tetap sama!","Ketika menghadapi kesulitan, satu cara tidak cukup, dapat menggunakan cara lain untuk menyelesaikannya, dan temukan jawabannya melalui pencarian.","Selalu bilang mulutku keras, sebenarnya hatiku sangat sapit dan baik.","Rumput busuk yang berubah menjadi kunang-kunang, bagaimana bisa dibandingkan dengan bulan yang terang dilangit?",},
        [24] = {24,"Apapun formasimu, nikmatilah, tidak akan kurang!","Puisi Jalan Sulit Shu, kesulitannya adalah untuk menghafal teks lengkapnya.","Darah merah menodai jubah sutera menembus Zirah, dan siapa yang berani berperang di depan!","Kuda bertemu orang cocok akan bersuara, orang bertemu teman akrab mati tanpa penyesalan.",},
        [25] = {25,"Aku ingin jadi lebih cepat, tinggi dan kuat!","Untuk mengajari seseorang, hanya perlu menguasai dua kalimat : 1. Lain kali sebelum melaksanakan sesuatu berpikirlah dua kali, 2. kau terlalu banyak berpikir.","Setiap hal tidak terduga, tiap tahun saldo tidak cukup!","Aku belum pernah bertemu dengan orang yang begitu tidak tahu malu!",},
        [26] = {26,"Tuhan akan membantu orang yang berusaha, jika kau mau pasti bisa!","Aku menabung Ingot untuk membuat Insignia Merah!","Tren perkembangan dunia adalah bahwa jika waktu perpecahan sangat panjang, akan ada persatuan pada waktu tertentu, ketika waktu persatuan sudah lama, akan ada perpecahan lagi pada waktu tertentu.","Di depan tidak ada jalan, mengapa para pasukan tidak berperang sampai mati?",},
        [27] = {27,"Orang yang mau diet tiap hari makan, bagaimana mau berhasil?","Menghindari orang yang suka berdebat, berteriaklah jika bertemu orang yang suka berlawanan, jika mood lagi jelek, hitunglah dari 1 sampai 99.","Walnut yang sudah terjepit pintu, masih bisa mengisi otakkah?","Wolong dan Pang Tong bersatu, dapat menenangkan dunia.",},
        [28] = {28,"Aku bertekad mengambil Juara I!","Paviliun langit tidak muat lagi, masukkan saja ke hatiku.","Tiap kali masuk TV membuka kotak berharga, selalu merasa ada yang mengintipku.","berkuda dengan Chitu ribuan mil, dengan pedang naga mengatasi segala kesulitan.",},
        [29] = {29,"Daripada sedih diam-diam, lebih baik segera beraksi.","Dulu aku ramping dan cantik, tetapi sekarang aku sudah tua dan gemuk.","Pria nangis bukanlah dosa, orang yang kuat juga memiliki hak untuk lelah.","Pria sejati berurusan dengan dunia, berusaha berkontribusi, mengutamakan kecepatan terlebih dahulu.",},
        [30] = {30,"Secepat apapun Roda Api Angin Sima Yi, juga tidak dapat dibandingkan denganku!","Sudah dikatakan bahwa menunggu selama seribu tahun, hasilnya mencapai perut dalam satu jam.","Apa kalian tahu, Da Qiao, Bu Lianshi, Diao Chan semuanya bisa nyanyi!","Berniat membasmi binatang harus mengorbankan tubuh untuk binatang.",},
        [31] = {31,"Xun Yu ada strategi adu domba, aku ada skill kaki berangin!","Kucing adalah hewan yang sakti, walau kau kaya atau miskin, dia tetap tidak akan menghargaimu.","Gubernur sangat gagah, sayang sekali jarang mengikuti kompetisi!","Hidup atau mati tidak akan melupakan suami!",},
        [32] = {32,"Orang yang selalu bersenang-senang, pasti akan kalah saat berlari!","Percaya atau tidak, jika aku lompat dapat menghancurkan tempurung lututmu!","Di lantai penuh dengan Kartu Avatar Xiao Qiao, kenapa ya?","Siapa orang bangun lebih dulu, aku mengetahuinya!",},
        [33] = {33,"Guo Jia memiliki Elang yang dapat terbang ribuan mil, tapi di arena ini pasti tidak bisa lari lebih cepat dariku!","Kalian semua sedang bercanda, aku akan mengatakan beberapa kata cinta yang kampungan!","Aku menemukan satu rahasia kecil, Taishi Ci saat mengeluarkan Skill menarik busur dengan kakinya!","Setelah perencanaan yang sempurna, bertemu lawan yang kuat, beradu kecerdasan bertemu dengan orang-orang yang tak terduga.",},
        [34] = {34,"Dengar-dengar Skill membalikkan luka Xiahou Dun sangat hebat? Tapi kalau untuk hal lari akulah nomor 1!","Biasanya orang yang tidak puas dengan model rambutnya, selamanya tidak akan mengakui kalau wajahnya bermasalah.","Dua bersaudara Sun Quan dan Sun Ce, satu di garis depan, satu di garis belakang!","Mengeluh pada saat aku miskin di Yuzhou, betapa beruntungnya di Nanyang ada Wolong!",},
        [35] = {35,"Cao Ren adalah siluman pintu, saat berlari aku paling tampan!","Sudah berniat libur sehari, tapi tidak disangka sudah datang hari esok!","Saat beruntung Lu Meng dapat mengalahkan enam orang!","Aku meminjam uang kepada teman programmerku, dia mentransfer uang 1024 Yuan, dengan pesan : jadikan pas.",},
        [36] = {36,"Tuanku cepat pergi, dengan begitu aku bisa mendapatkan juara I!","Jika minum air saja bisa gemuk, kenapa aku tidak minum Coca Cola saja?","Gaya Gan Ning berlari memikul pedang sangat lucu!","Pria sejati di dunia, tidak bisa berprestasi mewujudkan tujuan, sama seperti rumput tidak berguna?",},
        [37] = {37,"Palu Meteor milik Xu Chu beratnya 40 kg, dia pasti tidak cepat berlari!","Dompetku tebal, isinya surat hutang.","Sun Jian adalah pria pertama dengan perisai kebal tak terkalahkan.","Waktu masih panjang, kita akan bertemu lagi.",},
        [38] = {38,"Zhang Liao jago dalam serangan Ribuan Mil, Aku jago lari mendapatkan juara I!","Kaki yang cacat dan kasih persaudaraan memudar, Siapa yang berlari paling lucu?","Sun Shangxiang sangat cantik, DPS juga meledak-ledak!","Bisa serang seranglah, tidak bisa serang bertahanlah, tidak bisa bertahan larilah, tidak bisa lari menyerahlah, tidak bisa menyerah, matilah.",},
        [39] = {39,"4 wanita cantik pada masa Tiga Negara, aku paling suka Nyonya Zhen!","Banyak-banyaklah bercermin, banyak hal yang akan dimengerti olehmu.","Lu Xun bekerja sama dengan Sun Ce, sangat hebat!","Manusia merencanakan, tuhan yang menentukan. Jangan dipaksakan!",},
        [40] = {40,"Cao Pi menyerang sambil memeluk pinggang Nyonya Zhen, dia pasti tidak bisa lari dengan cepat!","Pernah bermimpi membawa pedang mengarungi dunia, kemudian tidak jadi karena sibuk kerja, karena selalu main game.","Lu Su juga bisa Skill pembuat pusing dan pengurang amarah!","Mendengar musik yang anggun mengetahui ambisi yang besar, dengan arak di cangkir berterima kasih kepada sahabat.",},
        [41] = {41,"Kaki pendek Yue Jin, tidak akan bisa berlari secepatku!","Asalkan batu, kemana saja pasti tidak akan bersinar.","Zuo Ci dan Zhuge, sangat berhati-hati!","Meskipun sesuatu bisa didapat dengan bicara, lebih baik diam untuk mendapatkannya.",},
        [42] = {42,"Orang adalah besi, Nasi adalah baja! Tidak makan gimana mau lari dengan cepat!","Sama-sama wajib belajar 9 tahun, kenapa kamu begitu menonjol.","Diao Chan membujuk Lu Bu, Cao Cao sakit hati melihatnya!","Langit seperti penutup, bumi seperti permainan catur.",},
        [43] = {43,"Zhao Yun menggendong A Dou masuk dan keluar dengan leluasa, pasti sangat cepat!","Aku ingin menjadi A Dou, siapa suruh dia memiliki harta negara!","Kalian cobalah menyerang Dong Zhuo yang ada di garis utama, sangatlah sulit!","Pasukan ada malam akan tenang, Jenderal mendengar tidak akan ada keributan.",},
        [44] = {44,"Liu Bei menang dengan kebaikan, tapi larinya tidak lebih cepat dariku!","Orang yang menciptakan kalimat mata anjing merendahkan orang pasti tidak pernah melihat kucing.","Hero yang akan dikejar sudah diperkuat, Hua Xiong juga!","Selama ini, ada menang pasti ada kalah, semuanya bergantian.",},
        [45] = {45,"Astronomi Wolong dapat mengetahui peristiwa dunia, kompetisi hari ini akulah juaranya!","Alam semesta tidak meledak, untuk turun dari tempat tidur saja malas; bumi tidak mulai kembali, jangan harap aku akan bangun lebih awal.","Luka Racun Jia Xu sangat hebat!","Sebagai Jenderal, mampu menekuk dan lurus, mampu lembut dan keras; mampu maju dan mundur, mampu lemah dan kuat.",},
        [46] = {46,"Yue Ying pernah memujiku sebagai orang yang pintar, juga memberitahuku cara mendapatkan juara I saat kompetisi!","Tidak ada yang tahu siapa adalah daun bawang, semua merasa sendiri dapat lari lebih cepat dari pedang sabit.","Gongsun Zan dapat membuat pusing dan mengurangi amarah, sangat berguna!","Semua sudah siap, cuma kurang angin timur.",},
        [47] = {47,"Betapa hebatnya Guan Yu, juga tidak akan secepat aku!","Tiap kali mau menyerah, tiba-tiba merasa masih ada harapan, dalam kompetisi ini tolong pilih aku!","Zhang Jiao dapat membuat orang diam, tidak takut dibuat diam orang lain!","Pria sejati hanya berpikir tentang karirnya, tidak memikirkan bisa dapat istri atau tidak?",},
        [48] = {48,"Tepat Sasaran, tua tapi kuat, Huang Zhong sangat hebat tapi tidak ada yang menggunakannya, dia akan sakit hati!","Jika masalah bertentangan dengan keinginan, ingatlah, ada pengaturan lain oleh takdir.","Kamu menyerang Yu Ji, ada kemungkinan keracunan!","Jika kau tidak mengecewakanku, aku pasti tidak akan mengecewakanmu.",},
        [49] = {49,"Ma Chao tidak berkuda, pasti tidak bisa lebih cepat dariku!","Kau selamanya tidak akan tahu, bahwa kau selamanya melupakan satu hal.","Yuan Shao bekerja sama dengan Lu Bu, sangat hebat!","Berpengetahuan luas, memperhitungkan masalah besar, ini adalah jalan penguasa.",},
        [50] = {50,"Lihat Jiang Wei memegang Crossbow Naga Emas, sama tidak dengan wasit kompetisi!","Dari dulu perasaan mendalam tidak abadi, selalu dengan cara mendapatkan hati orang.","Yuan Shu dapat menambah amarah teman dan mengurangi amarah musuh. Xiao Qiao juga memiliki skill seperti itu!","Aku yang beruntung masuk Rangking 50 besar di CP! semoga hari ini mendapatkan juara I!",},
    }
}

return play_horse_player