--story_general_plan

local story_general_plan = {
    -- key
    __key_map = {
      id = 1,    --锦囊关id-int 
      name = 2,    --锦囊名称-string 
      des = 3,    --帐篷事件描述-string 
    
    },
    -- data
    _data = {
        [1] = {1,"Tantangan Hero","Dong Zhuo, nama kehormatan Zhongying, Panglima perang Liangzhou pada masa akhir Negara Donghan, menjadi pejabat tinggi di Luoyang, menjabat sebagai Guru Agung, sangat berwewenang. Tubuhnya kekar, lengannya kuat, jago berkuda dan memanah, suka arak, suka makan daging, lebih suka wanita cantik. Kemudian, karena brutal membunuh orang tidak bersalah, mati terkena strategi orang cantik Diao Chan, Dipenggal oleh Lu Bu.",},
        [2] = {2,"Tantangan Hero","Sun Ce, nama kehormatan Bofu, dikenal sebagai Tirani Jiangdong, salah satu pendiri Dongwu. Saat muda, berpenampilan tampan, berpikiran terbuka, terkenal, kemudian mengikat saudara dengan Zhou Yu. Untuk mewarisi warisan Sun Jian, bergabung bersama Yuan Shu, setelah Yuan Shu menjadi Kaisar, Sun Ce memutus hubungan dengan Yuan Shu dan menyatukan Jiangdong.",},
        [3] = {3,"Tantangan Hero","Zhao Yun, nama kehormatan Zilong, Salah satu dari 5 Jenderal harimau Negara Shu Han. bertubuh tinggi, berwibawa, pernah keluar masuk dengan leluasa di Lereng Changban, menolong A Dou anak Liu Bei, Tuannya berkata : Zhao Yun sangat bernyali.",},
        [4] = {4,"Tantangan Hero","Zhang Fei, nama kehormatan Yide, salah satu dari 5 Jenderal pemberani Negara Han, bersama dengan Liu Bei dan Guan Yu saudara sumpah taman persik, sangat berani, sifatnya membara, dikenal benci terhadap kejahatan, pernah berteriak keras menakuti beratus ribu pasukan Cao Cao di Lereng Changban.",},
        [5] = {5,"Tantangan Hero","Zhou Yu, nama kehormatan Gongjin, Hero Negara Dongwu, Gubernur. Dipanggil Zhoulang karena berwajah tampan, jago musik, ada kiasan [musik ada kesalahan, Zhoulang membaikinya]. berhubungan baik dengan Sun Ce, membantu Sun Ce menstabilkan Jiangdong, Kemudian Sun Ce mati diserang, membantu Sun Quan menguasai Jiang Dong. Pada Tahun 208, Zhou Yu memimpin pasukan beraliansi dengan Liu Bei, mengalahkan pasukan Cao di Perang Chibi, dari situlah asal dunia terbagi tiga. Diberi gelar oleh generasi berikutnya [Pahlawan dunia yang berani, pria Jiangdong yang luar biasa].",},
        [6] = {6,"Tantangan Hero","Zhuge Liang, nama kehormatan Kongming, digelarkan Wolong, Perdana Menteri Negara Shu Han. Awalnya bertani di Longzhong, akhirnya keluar setelah tiga kali kunjungan oleh Liu Bei, membantu Liu Bei membangun Negara Shu Han. Pernah berhasil mengaliansikan Negara Wu dan Shu, strategi kosong mengejutkan Sima Yi, seumur hidup berjuang untuk tujuan besar Negara Shu Han, Merupakan simbol pejabat setia dan pintar. Salah satu karyanya yaitu Memorial Tahta Buku Firman dan lainnya, Pernah menciptakan Sapi Kayu, Lentera Kongming, Crossbow Zhuge dan lainnya.",},
        [7] = {7,"Tantangan Hero","Cao Cao, nama kehormatan Mengde, nama kecil A Man, panglima perang akhir masa Negara Han, pahlawan pengkianat sepanjang masa, adalah Pendiri sebenarnya Negara Wei, tidak hanya jago Strategi perang, juga musik, berpuisi, bergelar Kaisar Wei, anaknya Cao Pi membangun Negara Wei selanjutnya, dengan gelar Wudi, dinamakan Kaisar Weiwu.",},
        [8] = {8,"Tantangan Hero","Zuo Ci, nama kehormatan Yuanfang, Taoist pada masa akhir Negara Donghan, master lima klasik, astrologi, ramalan kuno, ilmu kebal, menurut legenda bisa memanggil hantu dan dewa, dengan ilmu itu terkenal di dunia, mendirikan perguruan dan ding.Zui ci pernah mempermainkan Cao Cao dan Sun Ce, kemudian masuk gunung melatih pil, mendapat ilmu pergi ke surga.",},
        [9] = {9,"Tantangan Hero","Lu Bu, nama kehormatan Fengxian, Hero kuat No.1 masa Tiga Negara. Senjatanya Halberd Surga, menunggangi Kuda Chitu, memakai mahkota emas, sikapnya luarbiasa, sangat berwibawa. Guan Yu, Zhang Fei, Liu Bei mengepungnya juga belum bisa menjatuhkannya, nama Dewa Perang memang cocok untuknya!",},
        [10] = {10,"Tantangan Hero","Diao Chan, salah satu Wanita cantik di masa Tiongkok Kuno, Anak angkat Wang Yun, istri Lu Bu. Memiliki kecantikan tiada tandingan dan bagai bulan, memiliki kecantikan yang dapat meruntuhkan negara. Demi membalas budi kepada Wang Yun ayah angkatnya, rela mengorbankan tubuhnya untuk menjalankan strategi membunuh Dong Zhuo.",},
        [11] = {11,"Tantangan Hero","Zhang Liao, nama kehormatan Wenyuan, Jenderal milik Lu Bu, kemudian mengikuti Cao Cao, salah satu dari 5 Jenderal pemberani Negara Cao Wei, Pernah memenggal Tadun, menghancurkan Wuheng. Tadun ke 21 Jian'an, Pasukan Dongwu mengepung Hefei, Zhang Liao memimpin beribu pasukan elit mengalahkan ratusan ribu pasukan Negara Wu, Hampir saja menangkap Sun Quan, kiasan anak kecil berhenti menangis berawal dari sini.",},
        [12] = {12,"Tantangan Hero","Sun Jian, nama kehormatan Wentai, pendiri Negara Dongwu, diberi gelar Macan Jiangdong, wajahnya tampan, lapang dada, jago menggunakan pedang, suka memakai sorban merah, pernah ikut serta dalam perang dengan Turban Kuning dan perang dengan Dong Zhuo.",},
        [13] = {13,"Tantangan Hero","Da Qiao, istri Sun Ce, orang cantik masa Tiga Negara, bersama adiknya Xiao Qiao dikenal sebagai Dua Qiao dari Jiangdong. Pintar musik dan puisi, kulitnya putih, matanya bagai lukisan, senyumnya bercahaya, sangat memikat orang.",},
        [14] = {14,"Tantangan Hero","Dian Wei, Hero Cao Cao, Bertubuh kekar, bertenaga kuat, mampu mengusir harimau. Jago menggunakan Halberd, pada saat Zhang Xiu berkhianat, mati demi melindungi Cao Cao.",},
        [15] = {15,"Tantangan Hero","Xiao Qiao, istri Zhou Yu, wanita cantik terkenal di Tiga Negara, bersama dengan kakaknya Da Qiao dikenal dengan Jiangdong 2 Qiao. Membuat roh melayang, memikat, lugu dan cemerlang, suara seperti lonceng perak, menawan dan bersemangat, tidak bisa tidak membuat orang menyukainya.",},
        [16] = {16,"Tantangan Hero","Yue Jin, nama kehormatan Wen Qian, salah satu dari 5 Jenderal Hebat Negara Cao Wei. Mengikuti Cao Cao karena keberaniannya, mengikuti militer bertahun-tahun, berperang kemana-mana, prestasinya sangat banyak. Meninggal di Jian'an saat berumur 23 tahun, dengan gelar kehormatan Marquis Wei.",},
        [17] = {17,"Tantangan Hero","Lu Lingju, menurut legenda adalah putri dari Lu Bu dan Diao Chan, cantik tidak kalah dari Diao Chan, Seni beladiri tidak kalah dari ayahnya, sangat anggun, pemberani. Walau memiliki tekad yang kuat pada saat menghadapi bahaya, tapi karena masa lalu yang kelam sangat takut akan kesepian.",},
        [18] = {18,"Tantangan Hero","Gan Ning, nama kehormatan Xingba, Hero Negara Dongwu. Suka berkelana pada usia muda, menancapkan bulu burung dikepalanya, memakai lonceng, memakai pakaian yang indah, berkelana ke seluruh penjuru mencuri harta di kapal, orang memanggilnya Pencuri Jin Fan. Setelah memasuki usia remaja dia berhenti mencuri, jago membaca puisi, pernah menjadi bawahan Liu Biao dan Huang Zu, kemudian membawa pasukan bergabung dengan Sun Quan, memulai prestasi. Pernah memimpin beratus orang menyerang Kamp Cao pada malam hari, banyak prestasi perang. Sun Quan pernah berkata:Cao Cao ada Zhang Liao, aku ada Gan Ning, seimbang.",},
        [19] = {19,"Tantangan Hero","Cao Ren, nama kehormatan Zixiao, Hero terkenal Negara Cao Wei pada masa Tiga Negara, salah satu dari 8 Jenderal pemberani Cao Wei, Tegas mengatur pasukan, jago bertahan. Mengikuti Cao Cao berperang dalam waktu lama, sangat berprestasi, menjabat Perdana Menteri.",},
        [20] = {20,"Tantangan Hero","Zhou Tai, nama kehormatan Youping, Hero Negara Dongwu. Beberapa kali melindungi Sun Quan pada saat perang, luka dibadan dimana-mana, seperti mengukir di atas kulit. Untuk memuji prestasi Zhou Tai, Sun Quan memberinya Payung Qingluo.",},
        [21] = {21,"Tantangan Hero","Nyonya Zhen, wanita cantik terkenal di masa Tiga Negara, nama lain Zhen Luo atau Zhen Fu, Ratu Wen Zhaozhen. Wanita yang sangat cantik, bertalenta dan elegan nomor satu didunia, awalnya adalah istri utama Kaisar Weiwen Cao Pi, tapi menurut legenda saling mencintai dengan Cao Zhi, menurut legenda (Berkat Dewi Luo) diciptakan Cao Zhi demi dia, kisah Dewi Luo diceritakan selama berabad-abad.",},
        [22] = {22,"Tantangan Hero","Huang Yueying, istri Zhuge Liang, putri Huang Chengyan orang terkenal Jingzhou. Menurut legenda, cantik tiada tara tapi pemalu, karena itu menutup wajahnya dengan kerudung. Dari keluarga terpelajar, sangat cerdas, bersama Zhuge Liang menciptakan Sapi Kayu, menjadi pembicaraan dunia.",},
        [23] = {23,"Tantangan Hero","Guan Ping, Hero Negara Shu Han, Putra Guan Yu, mengikuti Guan Yu menyerang utara, Beladiri sangat hebat, tidak kalah dari ayahnya, pernah mengikuti Liu Bei menyerang Xichuan, berprestasi perang, kemudian berperang 30 ronde dengan Pang De Jenderal kuat Negara Cao Wei, keduanya tidak dapat menentukan menang dan kalah.",},
        [24] = {24,"Tantangan Hero","Han Dang, nama kehormatan Yigong, Jenderal Dongwu. Jago memanah, berkuda dan kekuatan lengannya luar biasa, mengabdi kepada Sun Jian, Sun Ce dan Sun Quan tiga generasi, memiliki prestasi luar biasa, memiliki pengaruh yang penting terhadap stabilnya Jiangdong dan berdirinya Negara Wu.",},
        [25] = {25,"Tantangan Hero","Lu Meng, nama kehormatan Ziming, Hero Negara Dongwu, pernah menjabat Gubernur. Mulai ikut berperang pada umur 15 tahun, jago berperang, tapi belajar buku sedikit, kemudian Sun Quan membujuknya untuk belajar, baru mulai rajin belajar, saat Lu su datang ke Xunyang untuk berdiskusi dengan Lu Meng, sangat terkejut dengan kemajuannya. kemudian dengan berpisah 3 hari, Lu Meng dari Negara Wu memiliki kemajuan yang pesat. Prestasi paling terkenal Lu Meng adalah merebut Jingzhou, mengalahkan Guan Yu Hero Negara Shu Han, meninggalkan kiasan Pedagang Palsu.",},
        [26] = {26,"Tantangan Hero","Lu Xun, nama kehormatan Boyan, Jenderal Dongwu, pernah menjabat sebagai Gubernur, Jenderal Shangda, Perdana Menteri, Mengalahkan pasukan Shu Han yang dipimpin oleh Liu Bei di Yiling, terkenal dalam sekali perang.Lu Xun sangat dihormati oleh Sun Quan, pandangannya jauh ke depan, setia, dan kedudukan tinggi sepanjang hidupnya, dia dipuji sebagai pejabat masyarakat. Pemain suka menyebut Zhou Yu sebagai Gubernur Besar dan Lu Xun sebagai Gubernur Kecil.",},
        [27] = {27,"Tantangan Hero","Sima Yi, nama kehormatan Zhongda, orang bertalenta yang jarang ada, cerdas banyak strategi, berpengetahuan luas. Politikus Negara Wei, penasihat, pejabat tinggi Negara Wei, pendiri Negara Xijin",},
        [28] = {28,"Tantangan Hero","Guan Yu, nama kehormatan Yunchang, pemimpin dari 5 Jenderal pemberani Negara Han Shu. Memiliki jiwa keadilan, sangat setia, pemberani, meninggalkan pujian memenggal Hua Xiong sebelum arak dingin, menggosok tulang untuk mengeluarkan racun dan lainnya.",},
        [29] = {29,"Tantangan Hero","Xiahou Dun, nama kehormatan Yuanrang, Hero Negara Cao Wei, Jenderal bermata satu yang bersemangat. Berperang untuk keluarga Cao seumur hidupnya, sangat hemat, semua hadiah yang diterima dibagikannya kepada pasukan, seumur hidup tidak ada harta, sampai mati tidak ada peninggalan harta.",},
        [30] = {30,"Tantangan Hero","Sun Jian, nama kehormatan Wentai, keturunan dari ahli perang Negara Sun Wu, Hero pada masa akhir Negara Donghan, panglima perang, pendiri Negara Wu dalam Tiga Negara. Berani dan tabah, penampilan luar biasa, bersikap lapang dada, bertalenta, adalah harimau Jiangdong.",},
        [31] = {31,"Tantangan Hero","Cao Pi, nama kehormatan Zihuan, politisi dan sastrawan terkenal. Pendiri Negara Cao Wei. Ahli sipil dan militer dari kecil, banyak membaca, mengetahui banyak teori para filosof.",},
        [32] = {32,"Tantangan Hero","Xu Shu, nama kehormatan Yuanzhi, awalnya penasihat di bawah Liu Bei, membantu agar Wolong keluar, kemudian mengikuti Cao Cao, mengabdikepada Cao Cao, tapi seumur hidup tidak ada prestasi besar. Meninggalkan Kiasan Tubuh di kamp Cao hati di Negara Han.",},
        [33] = {33,"Tantangan Hero","Sun Quan, nama kehormatan Zhongmou, pendiri Negara Dongwu. Mengalahkan Cao Cao saat perang Chibi, menetapkan pola dunia terbagi tiga. Penampilannya unik, kekar, memiliki aura orang terhormat, ada perkataan terkenal yaitu jika ingin memiliki anak harus seperti Sun Quan.",},
        [34] = {34,"Tantangan Hero","Jia Xu, nama kehormatan Wenhe, orang Liangzhou, penasihat terkenal dalam Tiga Negara. Awalnya adalah bawahan Dong Zhuo, setelah Dong Zhuo mati, karena memberi strategi kepada Li Jue dan Guo Si menyerang balik Chang'an, maka dipanggil Penasihat beracun. Kemudian Jia Xu menjadi penasihat Zhang Xiu, Dan akhirnya menyerah pada Cao Cao menjadi penasihat Negara Cao Wei.",},
        [35] = {35,"Tantangan Hero","Guo Jia, nama kehormatan Fengxiao, Penasihat paling awal di negaa Wei, Salah satu dari 5 penasihat Negara Cao Wei, menjabat penasihat Jijiu. Sangat Cerdas, Banyak strategi, Cao Cao memanggilnya [Qizuo], tapi mati muda, Cao Cao sangat menyesalinya.",},
        [36] = {36,"Tantangan Hero","Pang Tong, nama kehormatan Shiyuan, bergelar Fengchu, penasihat penting Liu Bei, kecerdasannya setara dengan Zhuge Liang, dalam Perang Chibi, dia menghindari keributan Jiangdong, merekomendasikan Lu Su kepada Zhou Yu, dan memasuki Kamp Cao mempersembahkan strategi Rantai Berantai, membantu Zhou Yu menyerang dengan api mengalahkan Cao Cao.",},
        [37] = {37,"Tantangan Hero","Sun Shangxiang, adik wanita Sun Quan, menikah dengan Liu Bei saat perang Chibi. Dia sangat Cantik, Cerdik, berjiwa berontak, tidak kalah dengan Pria.",},
        [38] = {38,"Tantangan Hero","Zhang Jiao, pemimpin Turban Kuning pada masa akhir Negara Han, pencipta ajaran kedamaian, memiliki beratus ribu pengikut. Pada tahun 184, Zhang Jiao dengan slogannya Negara Han sudah berakhir, yang akan menggantikannya adalah kita pasukan Turban Kuning, tahun ke 184 Gongyuan, dunia akan damai. menyebut dirinya Jenderal Langit, memimpin semuanya melancarkan pemberontakan, terkenal dengan Pemberontakan Turban Kuning.",},
        [39] = {39,"Tantangan Hero","Zhang He, nama kehormatan Junyi, salah satu dari 5 Jenderal Hebat Negara Cao Wei. Pernah mengikuti Yuan Shao, Saat perang Guandu bergabung dengan Cao Cao. Zhang He bergabung dengan pasukan seumur hidupnya, menggunakan pasukan dengan terampil, jago menyusun formasi, pintar menggunakan kondisi medan perang, setelah mengikuti Cao Cao, membuat banyak prestasi.",},
        [40] = {40,"Tantangan Hero","Meng Huo, Barbarian Selatan, pemimpin suku kecil di daerah tengah selatan pada masa Tiga Negara, ditangkap dan dilepas 7 kali oleh Zhuge Liang, semenjak itu tidak lagi memberontak. Dia bukan saja berani dan bertekad kuat, juga sangat baik terhadap orang, sangat disukai di daerahnya.",},
    }
}

return story_general_plan