--team_recommend

local team_recommend = {
    -- key
    __key_map = {
      id = 1,    --阵容推荐ID-int 
      name = 2,    --阵容名称-string 
      title1 = 3,    --说明标题1-string 
      description1 = 4,    --说明内容1-string 
      title2 = 5,    --说明标题2-string 
      description2 = 6,    --说明内容2-string 
      title3 = 7,    --说明标题3-string 
      description3 = 8,    --说明内容3-string 
    
    },
    -- data
    _data = {
        [1] = {1,"Formasi DPS","Karakteristik Faksi","Wei memiliki $c5_kemampuan regen Amarah$ kuat, semua Hero memiliki talenta Regen Amarah, dengan kombinasi yang pas bisa menciptakan mode $c5_Otomatis$ | Otomatis yaitu setiap ronde memberikan regen cukup Amarah kepada Hero tertentu, membuat mereka mengeluarkan skill di setiap giliran | Mode Otomatis memiliki variasi dan fleksibilitas kuat, bisa berdasarkan keperluan dan Hero yang dimiliki, menciptakan formasi otomatis khasmu sendiri","Cara mengalahkan","$c5_Dian Wei$ DPS Kritikal tinggi, $c5_Xu Chu$ menghabisi musuh yang terluka, $c5_Zhang Liao$ menyerang baris belakang |$c5_Zhang He$ Skill perisai kebal, kemampuan proteksi bagi tim, $c5_Xun Yu$ Heal efektif dan juga konversi serangan yang diterima menjadi heal menjamin keberlangsungan hidup sekutu |Aktivasi $c5_Dian Wei+Xu Chu$, $c5_Zhang Liao+Zhang He$ kedua kombi ini, DMG yang dihasilkan sangat luar biasa","Analisa Hero","Posisi 1 $c5_Dian Wei$, DPS Kritikal tinggi, bisa melukai bahkan langsung membunuh musuh horizontal |Posisi 2 $c5_Zhang He$, Skill menyerang unit Hero musuh baris belakang, serta memberikan perisai kebal ke sekutu HP terendah, kemampuan proteksi luar biasa |Posisi 3 $c5_Xu Chu$, Skill menyerang musuh baris depan, juga ekstra serangan kritikal, kemampuan menghabisi musuh yang terluka |Posisi 4 $c5_Zhang Liao$, Skill menyerang musuh baris belakang, bisa bersama Dian Wei & Zhang He mengakibatkan serangan fatal terhadap Hero musuh baris belakang |Posisi 5 $c5_Xun Yu$, Heal super efektif, kemampuan regen berkembang saat menerima serangan, menjamin keselamatan tim |Posisi 6$c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang (semua posisi bisa ditukar)",},
        [2] = {2,"Formasi DPS Kontrol","Karakteristik Faksi","Wei memiliki $c5_kemampuan regen Amarah$ kuat, semua Hero memiliki talenta Regen Amarah, dengan kombinasi yang pas bisa menciptakan mode $c5_Otomatis$ | Otomatis yaitu setiap ronde memberikan regen cukup Amarah kepada Hero tertentu, membuat mereka mengeluarkan skill di setiap giliran | Mode Otomatis memiliki variasi dan fleksibilitas kuat, bisa berdasarkan keperluan dan Hero yang dimiliki, menciptakan formasi otomatis khasmu sendiri","Cara mengalahkan","Diam, Stun, Kebal, Heal, berbagai kontrol dan regen, mempermainkan musuh dengan mudah | $c5_Guo Jia$ membuat Diam musuh baris depan, $c5_Cao Ren$ Stun musuh horizontal, $c5_Xiahou Dun$ refleksi DMG kuat serta kemampuan regen, $c5_Zhang He$ proteksi Kebal, $c5_Xun Yu$ heal efektif | Aktivasi kombo $c5_Xiahou Dun + Cao Ren$, formasi memiliki kontrol dan proteksi efektif, mengurasi DMG yang diterima sekutu, juga mampu menghancurkan musuh","Analisa Hero","Posisi 1 $c5_Guo Jia$, Skill mengakibatkan Diam terhadap musuh baris depan, bisa membatasi musuh baris depan untuk mengeluarkan skill di ronde awal | Posisi 2 $c5_Cao Ren$, Skill Stun musuh horizontal, bisa membatasi musuh horizontal mengeluarkan skill di ronde awal | Posisi 3 $c5_Xiahou Dun$, Skill menyerang musuh horizontal, serta regen HP diri sendiri, juga memiliki kemampuan refleksi DMG kuat, efektif terhadap Hero tunggal musuh (Posisi 2 & 3 bisa ditukar) | Posisi 4 $c5_Xun Yu$, Kemampuan Heal efektif, Kemampuan regen saat menerima serangan selangkah lebih menjamin kemampuan bertahan hidup sekutu |Posisi 5 $c5_Zhang He$, skill menyerang unit musuh baris belakang, serta memberikan perisai kebal ke sekutu HP terendah, kemampuan proteksi yang sangat kuat|Posisi 6 $c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang (semua posisi bisa ditukar)",},
        [3] = {3,"Formasi Brutal","Karakteristik Faksi","Shu memiliki $c5_kemampuan DPS$ tinggi, dengan DMG tinggi dengan cepat menghabisi musuh |Menang dengan 1x skill, menang dengan cepat; juga bisa mengontrol musuh. Teknik perang bervariasi, kombinasi banyak sekali | Kombinasi berbeda akan menghasilkan efek berbeda, tujuannya adalah DMG tinggi, menikmati membunuh dengan cepat","Cara mengalahkan","$c5_Ma Chao$ memberikan perisai reduksi DMG ke baris depan; $c5_Liu Bei$Kemampuan heal dan konversi DMG skill yang diterima untuk heal tim, menjamin tim bertahan hidup |$c5_Zhang Fei, Guan Yu, Huang Zhong$ memiliki kemampuan DPS tinggi, membunuh musuh dengan cepat dan menyelesaikan duel |Aktivasi了$c5_Ma Chao + Huang Zhong$, $c5_Guan Yu + Zhang Fei$ kedua kombo ini, menghasilkan DMG pada level yang berbeda","Analisa Hero","Posisi 1 $c5_Ma Chao$, setelah mengeluarkan skill memberikan perisai reduksi DMG ke sekutu baris depan, meningkatkan kemampuan bertahan hidup sekutu | Posisi 2 $c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang | Posisi 3 $c5_Liu Bei$, Kemampuan heal dan konversi DMG skill yang diterima untuk heal tim, menjamin tim bertahan hidup | Posisi 4 $c5_Zhang Fei$, Skill menyerang musuh baris depan, semakin sedikit HP semakin tinggi DMG, kemampuan DPS sangat kuat | Posisi 5 $c5_Huang Zhong$, skill menyerang musuh baris depan, memiliki banyak cara ekstra serangan normal, menghabisi lawan dengan HP sedikit | Posisi 6 $c5_Guan Yu$ DPS unit baris depan kuat, kritikal tinggi, cocok melawan Hero pusat baris depan musuh (posisi 2,3,4,5,6 bisa ditukar)",},
        [4] = {4,"Formasi DPS Kontrol","Karakteristik Faksi","Shu memiliki $c5_kemampuan DPS$ tinggi, dengan DMG tinggi dengan cepat menghabisi musuh |Menang dengan 1x skill, menang dengan cepat; juga bisa mengontrol musuh. Teknik perang bervariasi, kombinasi banyak sekali | Kombinasi berbeda akan menghasilkan efek berbeda, tujuannya adalah DMG tinggi, menikmati membunuh dengan cepat","Cara mengalahkan","Menjamin kemampuan DPS, menambahkan kemampuan kontrol musuh $c5_Xu Shu$ dan serangan Pang Tong meningkat drastis | $c5_Zhang Fei & Guan Yu$ adalah DPS yang sangat kuat, aura serangan milik $c5_Pang Tong$ membuat DMG semakin besar |Aktivasi $c5_Pang Tonng + Xu Shu & Guan Yu + Zhang Fei$ kedua kombo ini, mengakibatkan DMG yang luar biasa","Analisa Hero","Posisi 1 $c5_Guan Yu$, DPS unit baris depan kuat, kritikal tinggi, cocok melawan Hero pusat baris depan musuh, memanfaatkan peluang |Posisi 2 $c5_Xu Shu$, Skill ekstra stun, efektif mengontrol Hero musuh baris belakang, mencegah skill keluar, menghambat DMG musuh |Posisi 3 $c5_Liu Bei$, Kemampuan heal dan konversi DMG skill yang diterima untuk heal tim, menjamin tim bertahan hidup |Posisi 4 $c5_Pang Tong$, memiliki banyak aura peningkat DMG, meningkatkan DMG Hero DPS secara maksimal |Posisi 5 $c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang |Posisi 6 $c5_Zhang Fei$, Skill menyerang musuh baris depan, semakin sedikit HP semakin tinggi DMG, kemampuan DPS sangat kuat (semua posisi bisa ditukar)",},
        [5] = {5,"Formasi DPS Kontrol","Karakteristik Faksi","Wu memiliki $c5_kemampuan Arson$ yang kuat, serta terhadap target yang Terbakar memiliki Bonus DMG & Kontrol Rate | Hero Arson adalah pusat tim, mengakibatkan musuh Terbakar, kemudian selanjutnya mengakibatkan DMG menggila pada musuh yang Terbakar |Kemampuan Hero Arson yang membakar luas, berbagai kombinasi tersedia untuk memaksimalkan keunggulan Tim Arson","Cara mengalahkan","Menemani kemampuan membakar baris depan milik $c5_Taishi Ci$, $c5_Lu Xun$ membakar baris belakang, menyerang musuh di semua posisi | $c5_Taishi Ci$ dikombinasi dengan $c5_Sun Quan$, terhadap musuh baris depan mengakibatkan DMG, $c5_Lu Xun$ dikombinasi dengan $c5_Gan Ning$, terhadap musuh baris belakang mengakibatkan DMG, $c5_Lu Meng$ terhadap target yang Terbakar berpeluang Stun, bertujuan sebagai kontrol | Aktivasi $c5_Taishi Ci + Sun Quan, Gan Ning + Lu Meng$ kedua kombo ini, DMG yang dihasilkan sangat luar biasa |$c5_Taishi Ci & Lu Xun$ kombinasi membakar menyeluruh, akan memaksimalkan skill $c5_Lu Meng$ untuk Stun semua musuh","Analisa Hero","Posisi 1 $c5_Taishi Ci$, Skill mengakibatkan musuh baris depan Terbakar | Posisi 2 $c5_Lu Xun$, Skill mengakibatkan musuh baris berlakang Terbakar (posisi 1 & 2 bisa ditukar) | Posisi 3 $c5_Lu Meng$, terhadap semua musuh mengakibatkan DMG, juga ekstra Stun, mengontrol musuh | Posisi 4 $c5_Sun Quan$, Skill mengakibatkan DMG terhadap musuh baris depan, terhadap target yang Terbakar ada bonus DMG | Posisi 5 $c5_Gan Ning$, Skill mengakibatkan banyak DMG terhadap unit musuh baris belakang, juga ekstra serangan, ada bonus DMG terhadap target yang terbakar, kemampuan kuat membunuh baris belakang |Posisi 6 $c5_Protagonis$ DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang (posisi 3, 4, 5 bisa ditukar)",},
        [6] = {6,"Formasi DPS Depan","Karakteristik Faksi","Wu memiliki $c5_kemampuan Arson$ yang kuat, serta terhadap target yang Terbakar memiliki Bonus DMG & Kontrol Rate | Hero Arson adalah pusat tim, mengakibatkan musuh Terbakar, kemudian selanjutnya mengakibatkan DMG menggila pada musuh yang Terbakar |Kemampuan Hero Arson yang membakar luas, berbagai kombinasi tersedia untuk memaksimalkan keunggulan Tim Arson","Cara mengalahkan","Menemani kemampuan membakar baris depan milik $c5_Taishi Ci$, terhadap baris depan mengakibatkan DMG dan kontrol, |$c5_Sun Shangxiang & Sun Quan$ terhadap musuh yang Terbakar, DMG & kritikal bertambah, $c5_Xiao Qiao$ terhadap target Terbakar ekstra efek Paralisis, kombinasi terhadap musuh baris depan mengakibatkan rentetan DMG & efek kontrol |Aktivasi kombo $c5_Taishi Ci +Sun Quan$, $c5_Da Qiao$ memberikan kemampuan bertahan hidup bagi tim, $c5_Xiao Qiao$ memberikan bonus yang cukup bagi DPS dalam tim","Analisa Hero","Posisi 1 $c5_Taishi Ci$, Skill mengakibatkan musuh baris depan Terbakar | Posisi 2 $c5_Sun Shangxiang$, skill mengakibatkan banyak DMG ke unit musuh baris depan, terhadap target yang Terbakar ada bonus DMG |Posisi 3 $c5_Sun Quan$, skill mengakibatkan DMG terhadap musuh baris depan, terhadap target yang Terbakar ada bonus DMG (posisi 2 & 3 bisa ditukar) | Posisi 4 $c5_Da Qiao$, skill dan serangan normal ekstra Heal berlanjut, meningkatkan kemampuan bertahan hidup sekutu |Posisi 5 $c5_Protagonis$,DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang (Posisi 4 & 5 bisa ditukar) |Posisi 6 $c5_Xiao Qiao$, skill terhadap target Terbakar akan ekstra paralisis, juga menyediakan bonus DMG terhadap sekutu",},
        [7] = {7,"Formasi DMG Racun","Karakteristik Faksi","Han memiliki $c5_kemampuan kontrol kuat$, juga kemampuan reduksi Amarah dan Racun | Kemampuan Kontrol bisa menghambat musuh dengan efektif; Kemampuan reduksi Amarah bisa memperlambat musuh mengeluarkan skill; DMG Racun sangat menonjol | Cara bermain tim kontrol bervariasi, kombinasi fleksibel, mencoba berbagai kombinasi kemampuan kontrol, melemahkan musuh, menghabisinya, dan meraih kemenangan","Cara mengalahkan","$c5_Jia Xu, Yu Ji$ skill ekstra efek Racun, memiliki DMG tinggi, durasi 2 ronde, semakin tinggi ronde, semakin tinggi DMG |$c5_Zhang Jiao, Gongsun Zan, Yuan Shao$ mengontrol musuh dengan efektif, memperpanjang jumlah ronde duel, membuat DMG Racun menjadi efektif | Jaminan DMG dan kontrol secara bersamaan, aktivasi $c5_Zhang Jiao+Yu Ji, Jiaxu+Gongsun Zan$ kedua kombo ini, DMG yang dihasilkan sangat luar biasa.","Analisa Hero","Posisi 1 $c5_Zhang Jiao$, Skill ekstra efek Diam, bisa membatasi skill musuh baris depan di awal ronde |Posisi 2 $c5_Gongsun Zan$, Skill ekstra Reduksi Amarah, bisa membatasi skill musuh baris belakang di awal ronde (Posisi 1 & 2 bisa ditukar) |Posisi 3 $c5_Jia Xu$, Skill ekstra efek Racun, bisa mengakibatkan DMG Racun 2 ronde terhadap musuh baris depan |Posisi 4 $c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang |Posisi 5 $c5_Yu Ji$, Skill ekstra efek Racun, bisa mengakibatkan DMG Racun 2 ronde terhadap 3 musuh acak (Posisi 3, 4, 5 bisa ditukar) |Posisi 6 $c5_Yuan Shao$, Skill ekstra efek Paralisis, mengakibatkan musuh di ronde 2 tidak bisa menyerang normal (Tidak bisa regen Amarah) , memperlambat penggunaan skill musuh ronde berikutnya, dengan tujuan memperpanjang ronde duel",},
        [8] = {8,"Formasi DPS Kontrol","Karakteristik Faksi","Han memiliki $c5_kemampuan kontrol kuat$, juga kemampuan reduksi Amarah dan Racun | Kemampuan Kontrol bisa menghambat musuh dengan efektif; Kemampuan reduksi Amarah bisa memperlambat musuh mengeluarkan skill; DMG Racun sangat menonjol | Cara bermain tim kontrol bervariasi, kombinasi fleksibel, mencoba berbagai kombinasi kemampuan kontrol, melemahkan musuh, menghabisinya, dan meraih kemenangan","Cara mengalahkan","$c5_Yu Ji, Hua Xiong$ memiliki kemampuan DPS yang baik, $c5_Dong Zhuo$ memiliki kemampuan bertahan hidup kuat, $c5_Zhang Jiao$ memiliki kemampuan kontrol |$c5_Hua Tuo$ kemampuan heal kuat, meningkatkan drastis kemampuan bertahan hidup sekutu | Menjamin DPS, aktivasi $c5_Zhang Jiao +Yu Ji, Dong Zhuo + Hua Xiong$ kedua kombo ini, DMg yang dihasilkan luar biasa","Analisa Hero","Posisi 1 $c5_Zhang Jiao$, Skill ekstra efek Diam, bisa membatasi skill musuh baris depan di awal ronde |Posisi 2 $c5_Dong Zhuo$, Skill ekstra Perisai Reduksi DMG, bisa mengurangi drastis DMG yang diterima, menghisap banyak DMG bagi sekutu |Posisi 3 $c5_Yu Ji$, Skill ekstra efek Racun, terhadap 3 musuh acak mengakibatkan Racun selama 2 ronde |Posisi 4 $c5_Hua Tuo$, kemampuan Heal yang kuat untuk melindungi tim, meningkatkan kemampuan bertahan hidup tim |Posisi 5 $c5_Protagonis$, DMG tidak bisa dianggap remeh, HP juga tidak sedikit, bisa bertahan & menyerang (Posisi 4 & 5 bisa ditukar) |Posisi 6 $c5_Hua Xiong$, Hero DPS kuat, terhadap musuh horizontal mengakibatkan banyak DMG(Posisi 3 & 6 bisa ditukar)",},
    }
}

return team_recommend