--team_recommend

local team_recommend = {
    -- key
    __key_map = {
      id = 1,    --阵容推荐ID-int 
      name = 2,    --阵容名称-string 
      title1 = 3,    --说明标题1-string 
      description1 = 4,    --说明内容1-string 
      title2 = 5,    --说明标题2-string 
      description2 = 6,    --说明内容2-string 
      title3 = 7,    --说明标题3-string 
      description3 = 8,    --说明内容3-string 
    
    },
    -- data
    _data = {
        [1] = {1,"Vĩnh Động Sát Thương Trận","Đặc Sắc","Ngụy có $c5_khả năng hồi nộ mạnh$, tất cả Tướng đều có thiên phú hồi nộ, có thể kết hợp tổ thành cách chơi $c5_Động Cơ Bất Tử$|Động Cơ Bất Tử tức là mỗi lượt giúp Tướng chỉ định hồi phục đủ lượng nộ khí, giúp Tướng mỗi lần ra tay đều có thể thi triển được kỹ năng|Cách chơi Động Cơ Bất Tử rất đa dạng và linh hoạt, có thể dựa trên Tướng đang có và nhu cầu cá nhân để tạo ra trận hình Động Cơ Bất Tử của riêng mình.","Cách Đánh","$c6_Tư Mã Ý$ PK sát thương cao có thể đánh tuyến tiên phong, $c5_Trương Liêu$ đột kích phía sau thu hoạch tàn dư|$c5_Trương Hợp$ kỹ năng kèm Thuẫn Vô Địch sẽ bảo vệ đồng đội, $c6_Tào Tháo$ sau khi đột phá có thể hồi nộ khí giúp đồng đội tăng xác suất thi triển kỹ năng, $c5_Tuân Úc$ trị liệu cao và trị liệu sau khi bị tấn công giúp đồng đội sinh tồn|Kích hoạt 2 nhóm $c6_Tư Mã Ý$ +$c5_Tuân Úc$, $c5_Trương Liêu +Trương Hợp$ hợp kích giúp tăng nhiều sát thương.","Phân tích Tướng","Vị trí 1 $c6_Tư Mã Ý$, sát thương PK cao, kết hợp kỹ năng truy kích của Thần Binh có thể diệt địch|Vị trí 2 $c5_Trương Liêu$, thi triển kỹ năng tấn công Võ Tướng hàng sau của địch, có thể thu hoạch sinh lực Võ Tướng hàng sau|Vị trí 3 $c5_Trương Hợp$, thi triển kỹ năng tấn công kẻ địch hàng sau, kèm hiệu quả Bảo Hộ Vô Địch phe ta. Sau khi đột phá giới hạn hồi phục Nộ Khí và tăng khả năng Bảo Hộ|Vị trí 4$c6_Tào Tháo$, tấn công kẻ địch hàng trước, hồi phục Nộ Khí phe ta, hỗ trợ tăng sinh lực|Vị trí 5$c5_Nhân vật$, sát thương và sinh lực đều cao, có thể chống đỡ cũng như tấn công (Có thể hoán đổi vị trí bất kỳ)|Vị trí 6 $c5_Tuân Úc$, trị liệu cực mạnh, trị liệu 3 mục tiêu phe ta, chị sát thương kỹ năng sẽ hồi sinh lực",},
        [2] = {2,"Cực Hạn Sát Thương Trận","Đặc Sắc","Ngụy có $c5_khả năng hồi nộ mạnh$, tất cả Tướng đều có thiên phú hồi nộ, có thể kết hợp tổ thành cách chơi $c5_Động Cơ Bất Tử$|Động Cơ Bất Tử tức là mỗi lượt giúp Tướng chỉ định hồi phục đủ lượng nộ khí, giúp Tướng mỗi lần ra tay đều có thể thi triển được kỹ năng|Cách chơi Động Cơ Bất Tử rất đa dạng và linh hoạt, có thể dựa trên Tướng đang có và nhu cầu cá nhân để tạo ra trận hình Động Cơ Bất Tử của riêng mình.","Cách Đánh","$c5_Điển Vi$ tấn công hàng dọc kẻ địch, $c5_Tào Phi$ tấn công phạm vi hình chữ thập, $c5_Hứa Chử$ tấn công hàng trước kẻ địch và thu hoạch, $c5_Chân Cơ$ hồi phục Nộ khí, $c5_Trương Liêu$ tấn công hàng sau kẻ địch|Kích hoạt nhóm  $c5_Điển Vi +Hứa Chử$ và $c5_Tào Phi+Chân Cơ$ hợp kích, trận hình sẽ có sát thương tối đa và diệt kẻ địch trong lượt tấn công đầu, dễ dàng chiến thắng.","Phân tích Tướng","Vị trí 1 $c5_Điển Vi$, dùng kỹ năng tấn công hàng dọc, sau khi đột phá giới hạn lượt đầu sẽ tăng mạnh sát thương và không tốn nộ|Vị trí 2 $c5_Tào Phi$, dùng kỹ năng tấn công chữ thập, khiến 4 kẻ địch giảm 4 sinh lực|Vị trí 3  $c5_Hứa Chử$, dùng kỹ năng tấn công hàng trước, diệt mục tiêu sẽ kèm đánh thường, khả năng kết liễu cực tốt|Vị trí 4 $c5_Chân Cơ$, bản thân hồi nộ nhanh, giúp đồng đội hồi nộ. Sau khi đột phá giới hạn có thể giải trừ Độc và Lửa, tăng mạnh khả năng sinh tồn phe ta, có thể kích hoạt hợp kích với Tào Phi.|Vị trí 5 $c5_Trương Liêu$, dùng kỹ năng tấn công địch hàng sau, dễ diệt gọn tướng sinh lực yếu phía sau|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [3] = {3,"Khống Chế Hậu Thủ Trận","Đặc Sắc","Ngụy có $c5_khả năng hồi nộ mạnh$, tất cả Tướng đều có thiên phú hồi nộ, có thể kết hợp tổ thành cách chơi $c5_Động Cơ Bất Tử$|Động Cơ Bất Tử tức là mỗi lượt giúp Tướng chỉ định hồi phục đủ lượng nộ khí, giúp Tướng mỗi lần ra tay đều có thể thi triển được kỹ năng|Cách chơi Động Cơ Bất Tử rất đa dạng và linh hoạt, có thể dựa trên Tướng đang có và nhu cầu cá nhân để tạo ra trận hình Động Cơ Bất Tử của riêng mình.","Cách Đánh","Trận Hình là trận hậu thủ, tận dụng ưu thế Ngụy, thời gian chiến đấu kéo dài|$c5_Tào Nhân$ tấn công hàng dọc kẻ địch, gây choáng mục tiêu. $c5_Hạ Hầu Đôn$ tấn công mục tiêu đơn thể, và phản sát thương kèm hồi sinh lực, $c5_Tuân Úc$ trị liệu Võ Tướng phe ta, hồi sinh lực khi bị tấn công, $c5_Chân Cơ$ hồi phục Nộ khí, $c6_Tào Tháo$ tấn công hàng trước kẻ địch, tăng sát thương đồng thời hồi phục nộ khí phe ta.|Trận Hình dùng khống chế của Tào Nhân để kéo dài tiết tấu của kẻ địch, dùng đặc tính vĩnh động của Ngụy và trị liệu của Tuân Úc để từ từ diệt đối phương, là trận hình mạnh dần.","Phân tích Tướng","Vị trí 1$c5_Tào Nhân$, thi triển kỹ năng tấn công hàng dọc kẻ địch và gây choáng mục tiêu. Đột phá giới hạn xác suất choáng tăng lên|Vị trí 2 $c5_Hạ Hầu Đôn$, thi triển kỹ năng tấn công mục tiêu đơn thể kẻ địch, phản sát thương, kẻ địch tấn công càng mạnh, phản sát thương càng mạnh, dựa vào sát thương phản đồn để hồi sinh lực. (Hạ Hầu Đôn có thể điều chỉnh theo vị trí sát thương kẻ địch)|Vị trí 3 $c5_Tuân Úc$, thi triển kỹ năng trị liệu mục tiêu phe ta, bị tấn công có thể trị liệu mục tiêu phe ta, tăng sinh tồn phe ta|Vị trí 4 $c5_Chân Cơ$, hồi Nộ Khí mạnh và giúp đồng đội hồi phục nộ khí. Đột phá giới hạn có thể giải độc, lửa tăng năng lực sinh tồn bản phe ta.|Vị trí 5 $c6_Tào Tháo$, thi triển kỹ năng tấn công Võ Tướng hàng trước kẻ địch, hồi phục Nộ khí Võ Tướng phe ta|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [4] = {4,"Sát Thương-Bạo","Đặc Sắc","Thục có $c5_khả năng sát thương lớn$, thông qua sát thương bạo kích nhanh chóng diệt kẻ địch|Áp dụng chiến thuật một đòn tất thắng để tốc chiến tốc thắng; hoặc khống chế kẻ địch, tiêu diệt dần dần? Chiến thuật đa dạng với nhiều tổ hợp|Tổ hợp khác nhau sẽ có hiệu quả khác nhau, mục đích đều nhằm tạo ra sát thương cao nhất, tận hưởng cảm giác diệt nhanh","Cách Đánh","$c5_Khương Duy$ tấn công mục tiêu hàng dọc, $c5_Trương Phi$ tấn công mục tiêu hàng trước, Khương Duy và Trương Phi tấn công sẽ áp chế sinh lực đối diện, giúp kỹ năng đơn thể của $c5_Quan Vũ$ dễ dàng diệt địch hơn, $c5_Ngụy Diên$ tấn công mục tiêu hàng dọc và khống chế kẻ địch, $c5_Bàng Thống$ cho hiệu quả sát thương vòng sáng cực mạnh|Kích hoạt 2 nhóm $c5_Khương Duy +Ngụy Diên$, $c5_Quan Vũ +Trương Phi$ hợp kích giúp bạo thương tăng nhiều.","Phân tích Tướng","Vị trí 1$c5_Khương Duy$, thi triển kỹ năng tấn công hàng dọc kẻ địch, Khương Duy ở lượt đầu sát thương mạnh nhất của Thục, có thể diệt thành viên đối phương|Vị trí 2 $c5_Quan Vũ$, tấn công mục tiêu đơn thể, thu hoạch sinh lực kẻ địch (Có thể hoán đổi với vị trí 4)|Vị trí 3 $c5_Ngụy Diên$, khống chế mục tiêu hàng dọc kẻ địch|Vị trí 4$c5_Trương Phi$, thi triển kỹ năng tấn công hàng trước kẻ địch, sinh lực càng thấp sát thương càng cao, có thể thu hoạch sinh lực cũng có thể áp chế sinh lực (Có thể hoán đổi với vị trí 2)|Vị trí 5 $c5_Bàng Thống$, thi triển kỹ năng tấn công hàng dọc kẻ địch và tăng sát thương phe ta, hồi phục nộ khí|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [5] = {5,"Khống Chế-ST","Đặc Sắc","Thục có $c5_khả năng sát thương lớn$, thông qua sát thương bạo kích nhanh chóng diệt kẻ địch|Áp dụng chiến thuật một đòn tất thắng để tốc chiến tốc thắng; hoặc khống chế kẻ địch, tiêu diệt dần dần? Chiến thuật đa dạng với nhiều tổ hợp|Tổ hợp khác nhau sẽ có hiệu quả khác nhau, mục đích đều nhằm tạo ra sát thương cao nhất, tận hưởng cảm giác diệt nhanh","Cách Đánh","Đảm bảo sát thương, tăng khả năng khống chế của $c6_Gia Cát Lượng$ và $c5_Ngụy Diên$, khả năng giảm sát thương của Hoàng Nguyệt Anh và khả năng hồi phục của $c5_Lưu Bị$|$c5_Ngụy Diên$ có thể khống chế hàng dọc, khiến địch không thể hành động, $c6_Gia Cát Lượng$ khống chế hàng sau, hình thành thế lấy nhiều đánh ít|$c5_Hoàng Nguyệt Anh$ có khả năng giảm sát thương và hồi nộ, là mắt xích khống chế quan trọng|$c6_Hoàng Trung$ tấn công và truy kích gây sát thương khá ổn, giúp bổ sung khả năng sát thương cho toàn đội hình","Phân tích Tướng","Vị trí 1 $c6_Gia Cát Lượng$, dùng kỹ năng gây Choáng địch hàng sau 1 lượt, sau khi đột phá khiến địch giảm nộ|Vị trí 2 $c5_Ngụy Diên$, gây Choáng cho địch hàng dọc, khống chế hàng dọc khá tốt, có thể làm gián đoạn kỹ năng và làm chậm sát thương từ địch|Vị trí 3  $c5_Hoàng Trung$, tấn công địch hàng trước, kèm đánh thường. Hoàng Trung đánh thường gây sát thương cao, mức chính xác và bạo kích thuộc nhóm dẫn đầu trong các tướng sát thương|Vị trí 4 $c5_Hoàng Nguyệt Anh$, giúp phe ta giảm sát thương phải chịu và hồi nộ, tăng mạnh khả năng chiến đấu liên tục|Vị trí 5 $c5_Lưu Bị$, giúp hồi sinh lực toàn phe ta, khi bị sát thương cũng có hiệu quả trị liệu, giúp bảo vệ phe ta khá tốt|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [6] = {6,"Phòng Ngự Tấn Công Trận","Đặc Sắc","Thục có $c5_khả năng sát thương lớn$, thông qua sát thương bạo kích nhanh chóng diệt kẻ địch|Áp dụng chiến thuật một đòn tất thắng để tốc chiến tốc thắng; hoặc khống chế kẻ địch, tiêu diệt dần dần? Chiến thuật đa dạng với nhiều tổ hợp|Tổ hợp khác nhau sẽ có hiệu quả khác nhau, mục đích đều nhằm tạo ra sát thương cao nhất, tận hưởng cảm giác diệt nhanh","Cách Đánh","Đặc điểm Trận Hình là sát thương liên tục|$c6_Triệu Vân$ càng đánh càng mạnh, mỗi lần thi triển kỹ năng hoặc đánh thường sẽ tăng sát thương cho Triệu Vân, kết hợp vòng sáng Giảm ST của $c5_Hoàng Nguyệt Anh$ và giảm thương hàng trước của $c5_Mã Siêu$ giúp Triệu Vân liên tục chiến đấu|Khống chế của $c5_Ngụy Diên$ và trị liệu của $c5_Lưu Bị$ tăng sinh tồn cho Triệu Vân, đây là điển hình của trận hình 4 bảo vệ 1","Phân tích Tướng","Vị trí 1 $c6_Triệu Vân$, dùng kỹ năng tấn công hàng dọc, bản thân tăng sát thương, sau khi đột phá đánh thường cũng gây thêm sát thương|Vị trí 2 $c5_Mã Siêu$, gây sát thương cho địch, đồng thời tăng khiên miễn giảm sát thương cho hàng trước phe ta, giúp tăng khả năng sinh tồn|Vị trí 3  $c5_Ngụy Diên$, dùng kỹ năng tấn công hàng dọc, có thể gây Choáng cho mục tiêu. Sau khi đột phá giới hạn có thể đánh Choáng thêm 1 mục tiêu|Vị trí 4 $c5_Hoàng Nguyệt Anh$, giúp phe ta giảm sát thương phải chịu và hồi nộ, tăng mạnh khả năng chiến đấu liên tục|Vị trí 5 $c5_Lưu Bị$, giúp hồi sinh lực toàn phe ta, khi bị sát thương cũng có hiệu quả trị liệu, giúp bảo vệ phe ta khá tốt|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [7] = {7,"Thiêu Đốt Sát Thương Trận","Đặc Sắc","Ngô có $c5_khả năng hỏa công mạnh$, với mục tiêu bị thiêu đốt có thể tăng tấn công và tăng tỉ lệ khống chế|Tướng hỏa công là nòng cốt của đội, thiêu đốt kẻ địch, sau đó gây sát thương bạo phát|Xoay quanh khả năng Tướng hỏa công có thể kết hợp thành nhiều tổ  hợp, phát huy tối đa ưu thế thiêu đốt","Cách Đánh","Kết hợp khả năng Thiêu Đốt của $c6_Chu Du$ với khả năng sát thương diện rộng của $c6_Tôn Sách$ và $c5_Tôn Quyền$, gây sát thương toàn phe địch|$c5_Tiểu Kiều$ dùng kỹ năng sẽ giúp hồi nộ toàn phe ta, tăng khả năng chiến đấu liên tục, $c5_Cam Ninh$ chuyên diệt mục tiêu sinh lực yếu|Kích hoạt tổ hợp $c6_Chu Du$+$c5_Tiểu Kiều$, gây sát thương hợp kích nhiều hơn","Phân tích Tướng","Vị trí 1 $c6_Chu Du$, dùng kỹ năng gây Thiêu Đốt toàn phe địch|Vị trí 2 $c6_Tôn Sách$, dùng kỹ năng gây sát thương lớn cho địch hàng sau, tăng nhiều sát thương lên mục tiêu bị Thiêu Đốt, có khả năng kết liễu hàng sau|Vị trí 3  $c5_Tiểu Kiều$, dùng kỹ năng hồi nộ toàn phe ta, Thần Binh tăng đến cấp nhất định, có thể dùng Khiên Vô Địch Hút SL bảo vệ mục tiêu phe ta|Vị trí 4 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)|Vị trí 5 $c5_Tôn Quyền$, dùng kỹ năng gây sát thương lớn cho địch hàng trước, gây thêm sát thương cho mục tiêu bị Thiêu Đốt, sau khi đột phá giới hạn có khả năng truy kích gây sát thương|Vị trí 6 $c5_Cam Ninh$, sát thương 1 mục tiêu, chuyên kết liễu mục tiêu sinh lực thấp",},
        [8] = {8,"Công Thủ Cân Bằng Trận","Đặc Sắc","Ngô có $c5_khả năng hỏa công mạnh$, với mục tiêu bị thiêu đốt có thể tăng tấn công và tăng tỉ lệ khống chế|Tướng hỏa công là nòng cốt của đội, thiêu đốt kẻ địch, sau đó gây sát thương bạo phát|Xoay quanh khả năng Tướng hỏa công có thể kết hợp thành nhiều tổ  hợp, phát huy tối đa ưu thế thiêu đốt","Cách Đánh","Kết hợp khả năng hỏa công toàn phe địch của $c5_Chu Du$, gây sát thương toàn phe địch|$c5_Tôn Thượng Hương$ gây thêm sát thương vào bạo kích cho mục tiêu bị Thiêu Đốt, $c5_Tiểu Kiều$ có thể gây Tê Liệt cho mục tiêu bị Thiêu Đốt và giúp phe ta hồi nộ, $c5_Đại Kiều$ trị liệu toàn phe ta, $c5_Tôn Kiên$ giúp giảm sát thương, đều có thể giúp bảo vệ tướng khác trong trận hình|Kích hoạt tổ hợp $c6_Chu Du$+$c5_Tiểu Kiều$ và $c5_Tôn Kiên$+$c5_Tôn Thượng Hương$, giúp tăng sát thương hợp kích","Phân tích Tướng","Vị trí 1 $c6_Chu Du$, dùng kỹ năng gây Thiêu Đốt toàn phe địch|Vị trí 2 $c5_Tôn Thượng Hương$, dùng kỹ năng tấn công 1 mục tiêu hàng trước, gây thêm sát thương cho mục tiêu bị Thiêu Đốt|Vị trí 3  $c5_Tiểu Kiều$, dùng kỹ năng hồi nộ toàn phe ta, Thần Binh tăng đến cấp nhất định, có thể dùng Khiên Vô Địch Hút SL bảo vệ mục tiêu phe ta|Vị trí 4 $c5_Đại Kiều$, dùng kỹ năng và đánh thường sẽ kèm trị liệu, tăng khả năng sinh tồn phe ta|Vị trí 5 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí 4, 5)|Vị trí 6 $c5_Tôn Kiên$, dùng kỹ năng gây sát thương 1 mục tiêu hàng trước và hồi sinh lực cho bản thân, sau khi đột phá có thể giúp đồng đội hấp thu sát thương",},
        [9] = {9,"Khống Chế Sát Thương Trận","Đặc Sắc","Ngô có $c5_khả năng hỏa công mạnh$, với mục tiêu bị thiêu đốt có thể tăng tấn công và tăng tỉ lệ khống chế|Tướng hỏa công là nòng cốt của đội, thiêu đốt kẻ địch, sau đó gây sát thương bạo phát|Xoay quanh khả năng Tướng hỏa công có thể kết hợp thành nhiều tổ  hợp, phát huy tối đa ưu thế thiêu đốt","Cách Đánh","Kết hợp khả năng hỏa công hàng trước/hàng sau của $c5_Thái Sử Từ/Lục Tốn$ và đặc tính sát thương hàng trước/hàng sau của $c5_Tôn Quyền$/$c6_Tôn Sách$ để gây sát thương, $c5_Tiểu Kiều$ có thể gây Tê Liệt cho mục tiêu bị Thiêu Đốt và giúp phe ta hồi nộ, $c5_Lữ Mông$ có thể gây Choáng cho tất cả mục tiêu bị Thiêu Đốt, $c5_Lỗ Túc$ có thể gây Choáng cho mục tiêu hàng dọc bị Thiêu Đốt","Phân tích Tướng","Vị trí 1 $c5_Thái Sử Từ$, dùng kỹ năng gây Thiêu Đốt địch hàng trước|Vị trí 2 $c5_Tôn Quyền$, dùng kỹ năng gây sát thương lớn cho địch hàng trước, gây thêm sát thương cho mục tiêu bị Thiêu Đốt|Vị trí 3  $c5_Tiểu Kiều$, dùng kỹ năng hồi nộ toàn phe ta, Thần Binh tăng đến cấp nhất định, có thể dùng Khiên Vô Địch Hút SL bảo vệ mục tiêu phe ta|Vị trí 4 $c5_Lữ Mông$, dùng kỹ năng tấn công toàn phe địch, gây Choáng cho mục tiêu bị Thiêu Đốt|Vị trí 5 $c5_Lỗ Túc$, dùng kỹ năng tấn công hàng dọc, gây Choáng cho mục tiêu bị Thiêu Đốt|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt (Có thể hoán đổi vị trí bất kỳ)",},
        [10] = {10,"Giảm Nộ Sát Thương Trận","Đặc Sắc","Quần Hùng có $c5_khả năng khống chế mạnh$, đồng thời có khả năng giảm nộ và sát thương độc|Khả năng khống chế tối đa kéo dài thời gian của kẻ địch; khả năng giảm nộ kéo dài thời gian thi triển kỹ năng của kẻ địch; khả năng duy trì sát thương trúng độc vô cùng nổi bật|Cách chơi đội khống chế đa dạng, linh hoạt, có thể áp dụng các tổ hợp khống chế khác nhau, giảm sức mạnh kẻ địch, giành chiến thắng","Cách Đánh","Kỹ năng của $c6_Lữ Bố$, $c5_Viên Thiệu$ sẽ có hiệu quả giảm nộ toàn bộ mục tiêu phe địch|$c6_Lữ Bố$, $c5_Hoa Hùng$ sát thương khá cao.|$c5_Hoa Đà$ giúp hồi phục sinh lực phe ta, sau khi đột phá còn có thể hồi sinh mục tiêu phe ta, $c5_Điêu Thuyền$ sau khi đột phá sẽ hồi phục nhiều nộ khí cho vị trí 1.|Kích hoạt $c6_Lữ Bố$ +$c5_Điêu Thuyền$ hợp kích, sát thương tăng nhiều","Phân tích Tướng","Vị trí 1 $c6_Lữ Bố$, thi triển kỹ năng tấn công toàn mục tiêu phe địch, giảm nộ khí kẻ địch, áp chế sinh lực đối diện|Vị trí 2 $c5_Hoa Hùng$, thi triển kỹ năng kèm hiệu qua Giảm Nộ, gây nhiều sát thương, thu hoạch sinh lực mục tiêu còn có thể kích hoạt Truy Kích|Vị trí 3 $c5_Viên Thiệu$,thi triển kỹ năng kèm Tê Liệt, cũng có thể gây Giảm Nộ với mục tiêu PK|Vị trí 4 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt|Vị trí 5 $c5_Hoa Đà$, thi triển kỹ năng trị liệu mục tiêu PK, đột phá có thể hồi sinh phe ta|Vị trí 6 $c5_Điêu Thuyền$, thi triển kỹ năng tấn công mục tiêu đơn thể, đột phá có thể hồi phục nhiều nộ khí vị trí 1",},
        [11] = {11,"Độc Thương Giảm Nộ Trận","Đặc Sắc","Quần Hùng có $c5_khả năng khống chế mạnh$, đồng thời có khả năng giảm nộ và sát thương độc|Khả năng khống chế tối đa kéo dài thời gian của kẻ địch; khả năng giảm nộ kéo dài thời gian thi triển kỹ năng của kẻ địch; khả năng duy trì sát thương trúng độc vô cùng nổi bật|Cách chơi đội khống chế đa dạng, linh hoạt, có thể áp dụng các tổ hợp khống chế khác nhau, giảm sức mạnh kẻ địch, giành chiến thắng","Cách Đánh","$c5_Vu Cát, Hoa Hùng$ có khả năng sát thương tốt, $c5_Đổng Trác$ có khả năng sinh tồn mạnh, $c5_Viên Thiệu$ có khả năng khống chế và giảm nộ toàn phe địch|$c5_Viên Thuật$ dùng kỹ năng tấn công 1 mục tiêu gây giảm nộ, đồng thời hồi nộ toàn phe ta|Đảm bảo sát thương, kích hoạt hai tổ hợp $c5_Đổng Trác+Hoa Hùng, Viên Thiệu+Viên Thuật$, hợp kích gây sát thương lớn hơn","Phân tích Tướng","Vị trí 1 $c5_Viên Thiệu$, thi triển kỹ năng kèm Tê Liệt, có thể gây  Giảm Nộ mục tiêu PK.|Vị trí 2 $c5_Hoa Hùng$, thi triển kỹ năng kèm Giảm Nộ, gây nhiều sát thương, thu hoạch sinh lực mục tiêu xong có thể kích hoạt Truy Kích|Vị trí 3 $c5_Vu Cát$, thi triển kỹ năng gây Trúng Độc với 3 mục tiêu ngẫu nhiên, đột phá giới hạn có thể giam Nộ khí kẻ địch|Vị trí 4 $c5_Viên Thuật$, thi triển kỹ năng gây sát thương mục tiêu đơn thể đồng thời giảm nhiều Nộ khí, hồi phục nộ khí toàn phe ta|Vị trí 5 $c5_Đổng Trác$, năng lực sinh tồn cao, khi bị tấn công sẽ giảm Nộ khí của người tấn công|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt",},
        [12] = {12,"Độc Thương Khống Chế Trận","Đặc Sắc","Quần Hùng có $c5_khả năng khống chế mạnh$, đồng thời có khả năng giảm nộ và sát thương độc|Khả năng khống chế tối đa kéo dài thời gian của kẻ địch; khả năng giảm nộ kéo dài thời gian thi triển kỹ năng của kẻ địch; khả năng duy trì sát thương trúng độc vô cùng nổi bật|Cách chơi đội khống chế đa dạng, linh hoạt, có thể áp dụng các tổ hợp khống chế khác nhau, giảm sức mạnh kẻ địch, giành chiến thắng","Cách Đánh","$c5_Vu Cát, Giả Hủ$ có sát thương cao, giúp giảm nhiều nộ khí kẻ địch, $c6_Tả Từ$, $c5_Công Tôn Toản$ có năng lực khống chế mạnh|$c5_Viên Thuật$ tấn công mục tiêu đơn thể, khi giảm nộ khí đơn thể đồng thời hồi phục nộ khí PK|Kích hoạt $c5_Giả Hủ+Công Tôn Toản$ giúp sát thương tăng cao","Phân tích Tướng","Vị trí 1 $c6_Tả Từ$, thi triển kỹ năng tấn công mục tiêu hàng trước và gây Choáng|Vị trí 2 $c5_Giả Hủ$, thi triển kỹ năng kèm Trúng Độc, gây nhiều sát thương đồng thời giảm Nộ khí kẻ địch hàng trước|Vị trí 3 $c5_Viên Thuật$, thi triển kỹ năng gây sát thương mục tiêu đơn thể đồng thời giảm nhiều nộ khí của mục tiêu, có thể hồi phục nộ khí toàn bộ phe ta.|Vị trí 4 $c5_Vu Cát$, thi triển kỹ năng gây Trúng Độc 3 mục tiêu ngẫu nhiên, đột phá giới hạn sẽ giảm nộ khí kẻ địch|Vị trí 5 $c5_Công Tôn Toản$, thi triển kỹ năng tấn công mục tiêu hàng sau và xác suất cao gây choáng|Vị trí 6 $c5_Nhân Vật$, tấn công ổn định, sinh lực không ít, đánh giỏi thủ tốt",},
    },

    -- index
    __index_id = {
        [1] = 1,
        [10] = 10,
        [11] = 11,
        [12] = 12,
        [2] = 2,
        [3] = 3,
        [4] = 4,
        [5] = 5,
        [6] = 6,
        [7] = 7,
        [8] = 8,
        [9] = 9,
    }
}

return team_recommend