--play_horse_player

local play_horse_player = {
    -- key
    __key_map = {
      rank = 1,    --名次-int 
      text_1 = 2,    --文本1-英语-string 
      text_2 = 3,    --文本2-英语-string 
      text_3 = 4,    --文本3-英语-string 
      text_4 = 5,    --文本4-英语-string 
    
    },
    -- data
    _data = {
        [1] = {1,"My CP stands for my strength! I will protect my love, my faith and my family forever!","I got the first place because I'm a nice player! I doubt if you can beat me with the same money I spent!","Who's gonna win? Check who's the No.1 player on the CP Rankings!","Sorry but I don't care who you are, all of you!",},
        [2] = {2,"C'mon! I'll win the first place today!","I'm the No.2 Warrior! Hahahaha!","Unlike someone, I always stay low-profile as No.2!","It's not that I want to be the protagonist. It's that I AM the protagonists!",},
        [3] = {3,"You missed the champion several times already, right? I'll be your right choice today!","Why are you so happy about it? Though I'm No.3 now, I can beat you right away!","Things happen on the battlefield. Those defeated may make a comeback at anytime.","Admitting defeat won't kill me, but I'd rather die than admit it!",},
        [4] = {4,"Pick me. You won't regret it!","Top 3 Warriors are so confident. I should stay low-profile as No.4.","You said Mine War was not fun at all, but you've mined for such a long time!","When will the new modes be released? Can't wait!",},
        [5] = {5,"Looks like you guys are having fun. Let me tell a few jokes.","Improve my CP everyday! That's my attitude towards this game!","A wise man always chooses the right lord to serve.","If you hear some sound from your knees when you crouch and stand up again, be careful, 'cause that probably means your ears work well.",},
        [6] = {6,"You're right! I don't want to be nobody!","My CP ranks No.6. It feels like I'm the symbol of good luck. Yay!","Water can float your boat. It can also be used to make porridge.","The leaders have big ambitions, while their underlings only care about the credit. It's like the water in the Yellow River, and I can do nothing about it!",},
        [7] = {7,"Mr. Big Shot, you're really witty!","I'm arrogant and unreliable, and I love laughing.","I almost have everything, but there's one thing I miss: you.","Throughout the whole game, I wasn't watching it. I was watching you.",},
        [8] = {8,"Someone has told a really bad joke.","I don't want to lose to the others!","Players' strength doesn't depend on their factions, but themselves.","Limit Break will be unlocked soon. By then our CP will be increased again!",},
        [9] = {9,"Which one do you think looks better, Da Qiao or Diao Chan?","To get the ninth place, I've been working hard to improve my CP everyday!","They say I love chatting, but actually I only want to talk with you.","No.1: Lu Bu, No.2: Zhao Yun, No.3: Dian Wei, No.4: Guan Yu, No.5: Ma Chao, No.6: Zhang Fei.",},
        [10] = {10,"I'm so happy to be one of top 10 fighters!","Looking for the most reliable? To the CP No.10 you go!","The wise focus on what they can do; The fool focus on what they can get.","How did you play this game? How come your CP is so high?",},
        [11] = {11,"So I should just give only because I may lose? How am I supposed to accept it without giving it a try?","So, I'm going to... win this game... in a rough way!","2018 World Cup in Russia: Argentina lost to the champion and the runner up.","Things happen, and fate is inevitable.",},
        [12] = {12,"Burn my passion for the game! Doesn't matter even if I lose it!","Wei Yan's Stun and Decrease Anger are really useful!","Who can tell which faction is more powerful?","Guan Yu risked his life to return the favor of Cao Cao. His gratefulness will be eulogized by the world forever.",},
        [13] = {13,"Do you still know who I am if I change my name?","Was running race even a thing in the real Three Kingdoms?","I am the wisest man in this world, waiting for my lord to appear.","Humans cannot decide their own fate.",},
        [14] = {14,"I want to win!","Pang Tong is really good after he reaches Breakthrough 10. Don't you know that?","Sun Ce is incredibly powerful when you need to take down enemies in the back row!","With a bottle of unrefined liquor, we can enjoy talking about things of all times.",},
        [15] = {15,"I really hope I can win this game sooner!","Train Xu Shu to clear the stories. That feels nice!","Wanna win? The key is, pick me!","There is always someone stronger. Those who use tricks will finally meet those of their kind.",},
        [16] = {16,"The game won't start before long. Let me tell some jokes.","I want to be the luckiest one! Divine Gears, Divine Warriors, come to me!","Scolding the shill is a kind of fun in this game.","One who keeps cultivating one's character can live a peaceful life. There is no need to leave a good name in history!",},
        [17] = {17,"Any billionaire would like to send a Double Red Packet?","Get a few more Divine Insignias and I'll beat that guy!","I've saved these crystals for so long. I can finally buy the Divine Insignia!","Children cannot bear the sound of lightning. The weak cannot stand the roar of a tiger.",},
        [18] = {18,"A real man can forgive women for their lies.","You're really noisy. Can you let me finish the race in silence?","Shh! Leave me alone. I miss her.","What are you doing? The only correct answer is: Talking to you.",},
        [19] = {19,"Since you won't come back, why would you remember me? Since we are destined to separate, why would you take the oath?","This is a serious race! Shut up, comedian!","I can love you all, but you must let me win!","You can't tell good from bad, which means your eyes are corrupted; You don't read, which means your mouth is corrupted; You don't listen to others' advice, which means your ears are corrupted.",},
        [20] = {20,"I won't let anyone underestimate me, except myself!","I'm a human, and you're not me, so you're not a human.","You are here for the game again, Pipa Spirit. You must have earned some from the tickets!","You don't know history, which means your brain is corrupted; You don't accept the seigneurs, which means your mind is corrupted; You plan to rise in rebellion, which means your heart is corrupted!",},
        [21] = {21,"How am I supposed to win the game in a graceful way?","A real man must not yield to others for too long!","I was defeated not because of god, but because the weather is hot!","It's boring during the waiting. Shall we scold the designer together?",},
        [22] = {22,"It will take patience and waiting though... I would like to be a Top 10 Fighter, too!","Having fun in the game is the top priority!","The leopard head can be happy as well!","Proud troops are destined to fail.",},
        [23] = {23,"I only follow my faith and I'll never regret it, never! ","Every cloud has a silver lining, but not yours.","They say my words sound mean, but actually I'm kind on the inside.","How will the shimmer of the decayed be brighter than the light of the moon?",},
        [24] = {24,"No matter what your lineup is, use it carefully and it will work!","Shakespeare's plays are difficult when you have to take a exam on it.","My armor was drenched in blood. Who dared fight me in Dangyang!?","One can die for one's real friends.",},
        [25] = {25,"I want to get faster, higher and stronger!","To teach someone a lesson, you only need two sentences: 1. Think twice before you act next time. 2. You were thinking too much.","Everything is not like what I expected, except my money: it's never enough!","I have never seen any one as shameless as you are.",},
        [26] = {26,"Heaven helps those who help themselves. Trust yourself!","I save Ingots to buy Divine Insignia!","The world tends to merge or separate when it has remained the same for too long.","We don't have a way out. Why not fight till the last breath?",},
        [27] = {27,"You want to lose weight, but you never go on a diet. How are you supposed to make it this way?","Stay away from the polemicists as they might ruin your day.","Will a nut affect us when it comes out?","Anyone served by the Lying Dragon or the Phoenix Fledgling can bring peace to the world.",},
        [28] = {28,"I'm determined to win the first place!","The roof is full, but you can still get into my heart.","Every time I was on TV when I opened a chest, it felt like people were peeping at me.","Riding Red Hare, one can go 1000 miles a day. Carrying the Green Dragon Crescent Blade, one can go through 5 passes alone.",},
        [29] = {29,"Rather than complain about it alone, you'd do something now.","I can't find my slim body anymore. All that I have now is regret and fat.","Just cry if you want, guys. Even the strongest one is allowed to feel tired.","A man should focus on making achievements.",},
        [30] = {30,"No matter how fast Sima Yi's wheels are, he won't catch up with me!","You said you would wait for me!","You know what, Da Qiao, Bu Lianshi and Diao Chan can sing!","To kill a beast, you must sacrifice yourself to get close to it.",},
        [31] = {31,"Xun Yu is able to play someone off against another, and I am able to run with the wind!","You can never understand cats, because no matter you're rich or poor, they all look down on you.","Marshal is so hot. Pity he seldom attends the race!","His will won't change even in the face of death. What a brave man!",},
        [32] = {32,"Those who sing while drinking will lose a running game!","I can jump up and break your knee. Wanna try, huh?","Xiao Qiao's Avatar Cards are all over the place. What happened?","Life is like a dream. Who can see everything in the dream? I can, and they are very clear to me! ",},
        [33] = {33,"Guo Jia has an eagle that can fly 10,000 miles, but I'm sure I can run faster than it!","You're all telling jokes. Let me tell some lame love words.","I found a secret: Taishi Ci pulls the bow with his leg when he uses skills!","He planned everything though, a man who was unexpectedly powerful showed up.",},
        [34] = {34,"They say Xiahou Dun has the incredible Reflection ability, huh? He still can't beat me in running!","In most cases, those who are dissatisfied with their haircut never admit that their faces don't look good at the beginning.","Sun Quan and Sun Ce are brothers. One takes care of enemies in the front row while the other takes care of those in the back row!","I had no resources when I was in Yuzhou. Luckily the Lying Dragon was in Nanyang!",},
        [35] = {35,"Cao ren is a door monster! I am the hottest one on the track!","We had a deal that this is once and for ever, but I never thought it's once and forever!","Lu Meng can stun 6 enemies when he's got luck!","I borrowed money from a programmer, and he transferred 1024 dollars to me. The note says: Here's a round number.",},
        [36] = {36,"Go, My Lord! So I can win the first place!","Since I get far for drinking water, why not drink coke?","Gan Ning looks funny when he runs with a sword on his shoulder!","What should a man do if he doesn't choose to make achievements? Die as a nobody?",},
        [37] = {37,"Xu Chu's meteor hammer weighs 80 pounds. He can't run fast!","My wallet is full, of IOU.","Sun Jian carries an invincible shield with him at the first round!","I will remember your favor forever.",},
        [38] = {38,"Zhang Liao is good at fighting long-distance battles, and I am good at winning the first place in running games!","Who's gonna be funnier when they run, Godly Kick or Kong Rong?","Sun Shangxiang looks the best, and she has very high DPS!","Take the next option when the last one no longer works: fight, defend, flee, surrender and die!",},
        [39] = {39,"Of the four beauties, I love Lady Zhen the best!","Look into the mirror when you can't figure out why something happens, and you'll see.","Lu Xun works well with Sun Ce!","Man proposes, god disposes. It's not up to you! ",},
        [40] = {40,"Cao Pi has to hold Lady Zhen when he uses Co-attack. He can't run fast!","I used to dream of travelling around the world as a chivalrous swordsman, but I didn't realize it because I've been busy playing games.","Lu Su can use Stun and Decrease Anger, too!","From the song I can learn your ambition. Let me thank you with the drink.",},
        [41] = {41,"Yue Jin's legs are short. He can't run as fast as I can!","As long as you are a stone, you'll never shine.","Zuo Ci and Zhuge can use hard control!","Rather than benefit from saying too much, I would stay silent.",},
        [42] = {42,"Food is the source of my energy! How am I supposed to run hungry!","We had the same education. How come you're so outstanding?","Diao Chan can restore Lu Bu's Anger by 4. That hurts Cao Cao badly!","The sky is like a round cover and the lands are like a chessboard. ",},
        [43] = {43,"Zhao Yun can go in and back from the battlefield with Adou in his arms. Sure he's fast!","I wanna become A Dou. 'cause he's got pandas!","Try challenge Dong Zhuo in the story. You are gonna cry!","Soldiers don't panic at night, and generals stay calm when there are accidents.",},
        [44] = {44,"Liu Bei can win people's trust with his virtue, but he can't run as fast as I can!","I'm sure those who think dogs are timeserving have never kept a cat.","All the Warriors with Pursuit have been enhanced, including Hua Xiong!","Since ancient times, prosperity and decline always come with each other.",},
        [45] = {45,"From the stargazing, I can predict I'll win the first place today!","I won't get up unless the whole universe is going to explode.","Jia Xu's poison damage is incredible!","As a general, one should have a flexible personality.",},
        [46] = {46,"Yueying once spoke highly of my intelligence, and she even told me how to win the first place!","No one knows who will be the victim, and everyone believes they can run faster than the scammer.","Gongsun Zan can use Stun and Decrease Anger. Nice choice for stories!","Everything is ready, and I only need a chance now.",},
        [47] = {47,"No matter how good Guan Yu is, he can't run as fast as I can!","Every time you want to give up you still think you got a chance, right? Pick me for this game!","Zhang Jiao can inflict Silence and he's immune to Silence!","Men only worry they can't achieve success. If you are successful, you don't even have to worry about getting a girl.",},
        [48] = {48,"Huang Zhong is old but still vigorous. This elite archer will be sad if no one picks him!","If things don't go the way you want, remember, that's not your fate.","Be careful when you take on Yu Ji. You may get poisoned!","If you don't fail me, I will never fail you.",},
        [49] = {49,"Ma Chao doesn't ride a horse, so he can't be as fast as I am!","You'll never know when you forget something forever.","Yuan Shao of Breakthrough 10 is amazing when he works with Lu Bu!","Mind about the bigger picture instead of details. That's what an emperor does.",},
        [50] = {50,"Look at Jiang Wei. He's carrying the Golden Dragon Crossbow. Don't you think he looks like a starter?","True love never beats tricks.","Yuan Shu can restore allies' Anger and use Decrease Anger on enemies. He's as useful as Xiao Qiao!","I'm lucky to be one of top 50 fighters! Hope I can get No.1 today!",},
    }
}

return play_horse_player