--story_general_plan

local story_general_plan = {
    -- key
    __key_map = {
      id = 1,    --锦囊关id-int 
      name = 2,    --挑战名称-英语-string 
      des = 3,    --帐篷事件描述-越南语-string 
    
    },
    -- data
    _data = {
        [1] = {1,"Warrior Challenge","Dong Zhuo, courtesy name Zhongying, was a Han in Liangzhou at the end of Eastern Han. Later he served the Emperor as Imperial Tutor in Luoyang and reigned the whole world with his great power. He had a towering body and strong arms, and was good at riding and archery. He loved liquor, meat, and especially beauties. His cruel reign drove Diao Chan and Lu Bu to kill him with a honey-trap.",},
        [2] = {2,"Warrior Challenge","Sun Ce, courtesy name Bofu, was called Jiangdong Overlord by people. This handsome and generous man was widely known when he was young, and later he became sworn brothers with Zhou Yu. To inherit Sun Jian's business after he died, he chose to serve Yuan Shu. Later Yuan Shu proclaimed himself emperor, which led to the rupture between him and Sun Ce, who later united Jiangdong.",},
        [3] = {3,"Warrior Challenge","Zhao Yun, courtesy name Zilong, was one of the Five Generals of Shu. This tall, imposing man once charged and withdrew in Changbanpo 7 times to rescue Liu Bei's son A Dou. His master said Zilong is filled with courage.",},
        [4] = {4,"Warrior Challenge","Zhang Fei, courtesy name Yide, was one of the Five Generals of Shu and the sworn brother of Guan Yu and Liu Bei. Known for his boldness and furious personality, he once frightened Cao Cao's force to run away with only a roar in Changbanpo.",},
        [5] = {5,"Warrior Challenge","Zhou Yu, courtesy name Gongjin, was Marshal of Wu. Known as Zhou the Youth for his handsome appearance, he was also a master of music. Therefore, the saying goes Zhou the Youth always knows when the music is wrong. He was Sun Ce's good friend and helped him suppress Jiangdong. Later when Sun Ce was assassinated, he helped Sun Quan reign Jiangdong again. In 208 AD, Zhou Yu allied with Liu Bei to defeat Cao Cao in Red Cliff, forming the situation of three kingdoms confronting each other. The people in later ages even have a saying to praise him Speaking of the heroes in this world, one must mention Zhou the Youth.",},
        [6] = {6,"Warrior Challenge","Zhuge Liang, courtesy name Kongming, nickname Lying Dragon, was the Prime Minister of Shu. He used to be a farmer in Longzhong before Liu Bei visited him three times to ask him to be his Prime Minister. He once helped form the alliance between Sun Quan and Liu Bei by debating against a group of scholars, and scared Sima Yi away by using the Empty Fort Strategy. As a symbol of loyalty and wisdom, he devoted his whole life to Shu. His works include the famous Chu Shi Biao and Jie Zi Shu. He even invented the wooden ox, the gliding horse, Kongming lantern and Zhuge Crossbow.",},
        [7] = {7,"Warrior Challenge","Cao Cao, courtesy name Mengde, nickname A Man, was a warlord at the end of Han and the real founder of Wei. He was good at military strategies as well as music and poems. The highest rank he reached when he was alive was King of Wei. After his son Cao Pi officially founded Wei, he received the posthumous title Emperor Wu of Wei.",},
        [8] = {8,"Warrior Challenge","Zuo Ci, courtesy name Yuanfang, was a famous Taoist and the founder of Sect of the Tripod at the end of Eastern Han. He had mastered the Five Classics, divination and Qimendunjia. Legend has it that he could tame gods and ghosts. He once played a trick on Cao Cao and Sun Ce. Later he focused on alchemy in the mountains and became an immortal in the end.",},
        [9] = {9,"Warrior Challenge","Lu Bu, courtesy name Fengxian, was the strongest general at the Three Kingdoms period. He usually fought with Sky Piercer, rode Red Hare and wore a golden crest. Liu Bei, Zhang Fei and Guan Yu once fought him together, but still they failed to defeat him. He deserves the title God of War!",},
        [10] = {10,"Warrior Challenge","Diao Chan, one of the Four Great Beauties of ancient China, was Wang Yun's adopted daughter and Lu Bu's wife. To thank Wang Yun for his upbringing, she sacrificed herself and used a honey-trap to kill Dong Zhuo.",},
        [11] = {11,"Warrior Challenge","Zhang Liao, courtesy name Wenyuan, was one of the Five Elite Generals of Wei. He used to be Lu Bu's General before serving Cao Cao. He once slayed Tadun and defeated Wuheng. In 216 AD, Wu's force of 100 thousand men attacked Hefei. Zhang Liao defeated them with only an elite force of thousands of men, and he almost capture Sun Quan. That was the origin of the story Zhang Liao Stopped Children from Crying.",},
        [12] = {12,"Warrior Challenge","Sun Jian, courtesy name Wentai, was the founder of Wu. Known as Tiger of Jiangdong, this handsome, generous man was good at using long blade and liked wearing red turban. He used to assault the Yellow Turban and Dong Zhuo.",},
        [13] = {13,"Warrior Challenge","Da Qiao, a famous beauty during Han, Sun Ce's wife, could play music and write poems. She was known as one of the Two Qiaos in Jiangdong. The other one was her younger sister, Xiao Qiao. Her skin was as white as snow and her eyes were as charming as a picture. Everyone would fall for her smile.",},
        [14] = {14,"Warrior Challenge","Dian Wei, Cao Cao's general, was a towering man strong enough to fight a tiger. This halberd user fought to the last breath to protect Cao Cao when Zhang Xiu betrayed them.",},
        [15] = {15,"Warrior Challenge","Xiao Qiao, Zhou Yu's wife, one of the famous beauties during the Three Kingdoms period, was known as one of the Two Qiaos in Jiangdong. The other one was her elder sister, Da Qiao. Her voice is sweet and her personality was so pure and energetic that everyone would like her.",},
        [16] = {16,"Warrior Challenge","Yue Jin, courtesy name Wenqian, was one of the Five Elite Generals of Wei. Known for his boldness, he had made countless achievements for Cao Cao. He died in 218 AD and got the posthumous title Marquis Wei.",},
        [17] = {17,"Warrior Challenge","Lu Lingju was said to be Lu Bu and Diao Chan's daughter. She was as beautiful as Diao Chan and as valorous as Lu Bu. On the battlefield, she was always the one charging in the front. Although she was brave enough to confront difficulties, she was afraid of loneliness due to her past. ",},
        [18] = {18,"Warrior Challenge","Gan Ning, courtesy name Xingba, was a general of Wu. When he was young, he was a pirate wearing feathers, bells and fancy clothes, known as the Well-dressed Pirate. Later he stopped pirating to study. In his life, he served Liu Biao, Huang Zu and Sun Quan in order. He once led a hundred men to raid Cao Cao's camp at night and made great achievements. Sun Quan once said Mengde has Zhang Liao, but I have Gan Xingba. They can match each other.",},
        [19] = {19,"Warrior Challenge","Cao Ren, courtesy name Zixiao, was one of the eight Tiger Cavalries of Wei. This strict general was good at defense. He had followed Cao Cao on the battlefield for many years and had made a lot of achievements. His rank reached War Minister in the end.",},
        [20] = {20,"Warrior Challenge","Zhou Tai, courtesy name Youping, was an important general of Wu. He had protected Sun Quan so many times that he had tens of wounds in his body. Sun Quan appointed him as a Senior Official to reward him.",},
        [21] = {21,"Warrior Challenge","Lady Zhen, a famous beauty during the Three Kingdoms period, was called Zhen Luo, Zhen Fu or Empress Zhen. This indescribable beauty was Emperor Wen of Wei, Cao Pi's first wife. Legend has it that she actually loved Cao Zhi and that Ode to Luo Goddess was written by Cao Zhi for her.",},
        [22] = {22,"Warrior Challenge","Huang Yueying, Zhuge Liang's wife, was daughter of Huang Chengyan, a celebrated scholar in Jingzhou. Rumor had it that she was incredibly beautiful, but she was so shy that she usually covered her face with a veil. Born to a knowledgeable family, she used her unusual talent to invent the Wooden Ox and the Gliding Horse with Zhuge Liang, which later became a popular story among the people.",},
        [23] = {23,"Warrior Challenge","Guan Ping, a general of Shu, Guan Yu's son, was as valorous as his father. He attended Liu Bei's expedition to Xichuan and made achievements. Later he fought Wei's general Pang De for 30 rounds, but the fight was too close to call.",},
        [24] = {24,"Warrior Challenge","Han Dang, courtesy name Yigong, was a general of Wu. Good at archery and riding, he had extraordinary arm strength. He had made great achievements after serving Sun Jian, Sun Ce and Sun Quan. He had a profound influence on the stabilization of Jiangdong and the founding of Wu.",},
        [25] = {25,"Warrior Challenge","Lu Meng, courtesy name Ziming, was once Marshal of Wu. He joined the army at the age of 15. Although he was good at fighting, he hardly read books at that time. Later persuaded by Sun Quan, he started to study hard. Lu Su was amazed at the progress he made when he came to Xunyang to have a meeting with Lu Meng. That was the origin of the story Ah Meng under Wu. His most famous achievement was the attack to Jingzhou, in which he defeated Guan Yu and left the story Fake Merchants.",},
        [26] = {26,"Warrior Challenge","Lu Xun, courtesy name Boyan, was a general of Wu. He used to be Wu's Marshal, Upper Grand General and Prime Minister. He became famous after beating Liu Bei in Yiling. Sun Quan had always valued him as this wise and loyal man devoted his whole life to Wu. Players are used to call Zhou Yu Marshal and Lu Xun Little Governor.",},
        [27] = {27,"Warrior Challenge","Sima Yi, courtesy name Zhongda, had been special person since childhood. He was wise, knowledgeable and ambitious, and he believed in Confucianism. He was a politician, a military strategist and a minister of Wei, and the founder of Western Jin.",},
        [28] = {28,"Warrior Challenge","Guan Yu, courtesy name Yunchang, was the leader of the Five Generals. There are many legends about this loyal and bold warrior, such as Kill Hua Xiong Before Wine Cools and Hua Tuo Heals Guan Yu's arm.",},
        [29] = {29,"Warrior Challenge","Xiahou Dun, courtesy name Yuanrang, was a famous general of Wei with only one eye. This furious but upright leader always shared his rewards with his underlings. Even if he devoted his whole life to the Cao family, he didn't have any legacy when he died.",},
        [30] = {30,"Warrior Challenge","Sun Jian, courtesy name Wentai, the descendant of Militarist Sun Wu, was a warlord at the end of Eastern Han and the founder of Wu. Bold and generous, he was known as the Tiger of Jiangdong.",},
        [31] = {31,"Warrior Challenge","Cao Pi, courtesy name Zihuan, Cao Cao's second son, was a famous politician, litterateur and the first emperor of Wei. He had practiced martial arts and had read countless books since childhood and was familiar with all the classics.",},
        [32] = {32,"Warrior Challenge","Xu Shu, courtesy name Yuanzhi, was Zhuge Liang's recommender and once Liu Bei's strategist. Later he was forced to serve Cao Cao, but he didn't make any great achievements all his life. That was the origin of the old saying His body is in Cao Cao's camp, but his heart is actually with Han.",},
        [33] = {33,"Warrior Challenge","Sun Quan, courtesy name Zhongmou, was Sun Jian's son and the founder of Wu. He defeated Cao Cao in Battle of Red Cliff, forming the situation of three kingdoms confronting each other. His appearance was incredibly outstanding and it seemed to imply his unusual fate. Cao Cao even said I wish I could have a son like Sun Quan.",},
        [34] = {34,"Warrior Challenge","Jia Xu, courtesy name Wenhe, was a famous strategist from Liangzhou. He was called Poison Strategist by people for suggesting Li Jue and Guo Si to fight back to Chang'an. Later he surrendered to Cao Cao and became an important strategist of Wei's Zhang Xiu.",},
        [35] = {35,"Warrior Challenge","Guo Jia, courtesy name Fengxiao, was one of the five strategists of Wei and even the most outstanding one at the early period. As Chief of Military Adviser, he was extremely intelligent. Cao Cao even called him [Incredible Assistant], but he died at a young age, which Cao Cao considered as a great loss.",},
        [36] = {36,"Warrior Challenge","Pang Tong, courtesy name Shiyuan, known as Phoenix Fledgling, was an important strategist of Liu Bei. His intelligence enjoyed the same fame as Zhuge Liang's. In Battle of Red Cliff, he stayed in Jiangdong to avoid from wars, and was recommended to Zhou Yu by Lu Su. Later he suggested Cao Cao to connect his ships, which helped Zhou Yu defeat Cao Cao completely.",},
        [37] = {37,"Warrior Challenge","Sun Shangxiang, Sun Quan's sister, married Liu Bei in Battle of Red Cliff. Beautiful, clever and unruly, she was an actual heroine.",},
        [38] = {38,"Warrior Challenge","Zhang Jiao, leader of the Yellow Turban, founder of Way of the Taiping, had hundreds of thousands believers. In 184 AD, he created a slogan The Azure Sky is already dead; The Yellow Sky will soon rise. When the year is jiazi, there will be prosperity under Heaven! and led the people to rise to rebellion, which became the famous Yellow Turban Rebellion in history.",},
        [39] = {39,"Warrior Challenge","Zhang He, courtesy name Junyi, was one of the Five Elite Generals of Wei. Before Battle of Guandu, he used to serve Yuan Shao. He spent most of his life fighting on the battlefield, and he was known for being good at using different formations and terrains. He had made many achievements since he started to serve Cao Cao.",},
        [40] = {40,"Warrior Challenge","Meng Huo, Southern Barbarian King, was the leader of the minority in the middle and southern regions. He sincerely surrendered after being captured and released 7 times by Zhuge Liang. He was bold on the battlefield and had firm will, which won him the trust of the locals.",},
    }
}

return story_general_plan