--team_recommend

local team_recommend = {
    -- key
    __key_map = {
      id = 1,    --阵容推荐ID-int 
      name = 2,    --阵容名称-英语-string 
      title1 = 3,    --说明标题1-英语-string 
      description1 = 4,    --说明内容1-英语-string 
      title2 = 5,    --说明标题2-英语-string 
      description2 = 6,    --说明内容2-英语-string 
      title3 = 7,    --说明标题3-英语-string 
      description3 = 8,    --说明内容3-英语-string 
    
    },
    -- data
    _data = {
        [1] = {1,"DPS Lineup","Faction Feature","Wei has powerful $c5_Anger restoring abilities$. All the warriors of Wei have Anger restoring Talents. Combine them reasonably and you will have a $c5_perpetual motion machine$.|Having a perpetual motion machine means you can restore enough Anger for a specific warrior every round, allowing them to use skill in every attack.|Perpetual motion machine is a flexible mode. You can build your own one according to the warriors you have and what you exactly need.","How to use","$c5_Dian Wei$ has high damage, $c5_Xu Chu$ can launch last blows while $c5_Zhang Liao$ can attack enemy's back row.|$c5_Zhang He$'s skill can protect allies with an invincible shield, $c5_Xun Yu$ does efficient healing and his healing upon being attacked further improves the team's survivability.|Activate two Combo Skills: $c5_Dian Wei + Xu Chu$, $c5_Zhang Liao + Zhang He$ to further increase the damage.","Warrior Analysis","Position 1: $c5_Dian Wei$ deals huge damage with his high Crit to significantly reduce the HP of enemy's middle row or even to kill them directly.|Position 2: $c5_Zhang He$ uses skill to attack one enemy in the back row and to protect the ally with the lowest HP with Invincibility.|Position 3: $c5_Xu Chu$ uses skill to attack enemy's front row and to launch Pursuit that will definitely trigger critical hit.|Position 4: $c5_Zhang Liao$ uses skill to attack enemy's back row. Cooperating with Dian Wei and Zhang He, he can launch a lethal blow to enemies.|Position 5: $c5_Xun Yu$ does efficient healing and his healing upon being attacked further improves the team's survivability.|Position 6: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage. (All positions can be switched)",},
        [2] = {2,"DPS Control Lineup","Faction Feature","Wei has powerful $c5_Anger restoring abilities$. All the warriors of Wei have Anger restoring Talents. Combine them reasonably and you will have a $c5_perpetual motion machine$.|Having a perpetual motion machine means you can restore enough Anger for a specific warrior every round, allowing them to use skill in every attack.|Perpetual motion machine is a flexible mode. You can build your own one according to the warriors you have and what you exactly need.","How to use","Fool your enemies with Silence, Stun, Invincibility and healing.|$c5_Guo Jia$ can inflict Silence on enemy's front row, $c5_Cao Ren$ can inflict Stun on lengthwise enemies, $c5_Xiahou Dun$ has Staunch Reflection and self healing, $c5_Zhang He$ has Invincibility and $c5_Xun Yu$ has efficient healing.|This lineup is designed to reduce the team's damage taken by using all kinds of controls and protections. By activating the Combo Skill: $c5_Xiahou Dun + Cao Ren$, you can eliminate enemies after the defense.","Warrior Analysis","Position 1: $c5_Guo Jia$ uses skill to inflict Silence on enemy's front row, banning them from using skill on the first round.|Position 2: $c5_Cao Ren$ uses skill to inflict Silence on enemy's middle row, banning them from using skill on the first round.|Position 3: $c5_Xiahou Dun$ uses skill to attack enemy's middle row and to restore self HP. His Staunch Reflection can counter enemy's single-targeted warrior. (Position 2 and 3 can be switched)|Position 4: $c5_Xun Yu$ does efficient healing and his healing upon being attacked further improves the team's survivability.|Position 5: $c5_Zhang He$ uses skill to attack one enemy in the back row and to protect the ally with the lowest HP with Invincibility.|Position 6: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage. (All positions can be switched)",},
        [3] = {3,"Violent DPS Lineup","Faction Feature","Shu has high $c5_DPS$, which allows them to destroy enemies very quickly.|Eliminate enemies with one blow or control them first to take them out one by one? A variety of strategies are optional.|Different combinations have different effects. They can all bring you the highest DPS.","How to use","$c5_Ma Chao$ can provide a shield for the front row in advance and $c5_Liu Bei$'s powerful healing and AOE healing upon being attacked guarantee the team's survivability.|$c5_Zhang Fei, Guan Yu and Huang Zhong$ can deal huge damage to eliminate enemies in an instant.|Activate two Combo Skills: $c5_Ma Chao + Huang Zhong$, $c5_Guan Yu + Zhang Fei$ to further increase the damage.","Warrior Analysis","Position 1: $c5_Ma Chao$ uses skill to inflict a shield for the team's front row, improving the team's survivability.|Position 2: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage.|Position 3: $c5_Liu Bei$'s powerful healing and AOE healing upon being attacked guarantee the team's survivability.|Position 4: $c5_Zhang Fei$ uses skill to attack enemy's front row. The less the HP, the higher the damage.|Position 5: $c5_Huang Zhong$ uses skill to attack enemy's front row and he has various ways to launch Pursuit and the last blow.|Position 6: $c5_Guan Yu$ deals huge damage to one enemy in the front row. His high Crit makes him suitable for focusing on one core warrior in enemy's front row. (Position 2, 3, 4, 5 and 6 can be switched)",},
        [4] = {4,"DPS Control Lineup","Faction Feature","Shu has high $c5_DPS$, which allows them to destroy enemies very quickly.|Eliminate enemies with one blow or control them first to take them out one by one? A variety of strategies are optional.|Different combinations have different effects. They can all bring you the highest DPS.","How to use","With damage guaranteed, $c5_Xu Shu$'s control abilities and Pang Tong's ATK buff are added.|$c5_Zhang Fei and Guan Yu$ can still deal huge damage while $c5_Pang Tong$'s ATK aura can further increase it.|Activate two Combo Skills: $c5_Pang Tong + Xu Shu, Guan Yu + Zhang Fei$ to further increase the damage.","Warrior Analysis","Position 1: $c5_Guan Yu$ deals huge damage to one enemy in the front row. His high Crit makes him suitable for focusing on one core warrior in enemy's front row.|Position 2: $c5_Xu Shu$ uses skill to inflict Stun, which can interrupt the skill of the corresponding warrior in enemy's back row.|Position 3: $c5_Liu Bei$'s powerful healing and AOE healing upon being attacked guarantee the team's survivability.|Position 4: $c5_Pang Tong$ has multiple auras that can improve allies' damage to the highest.|Position 5: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage.|Position 6: $c5_Zhang Fei$ uses skill to attack enemy's front row. The less the HP, the higher the damage. (All positions can be switched)",},
        [5] = {5,"DPS Control Lineup","Faction Feature","Wu is good at $c5_inflicting Burning$, and their warriors enjoy ATK bonuses and control chance bonuses when they attack targets who are Burning.|Arson warriors are the core of the team. Inflict Burning on enemies and deal burst damage to them.|Carry out a series of attacks with arson warriors as the core to make good use of the advantage of Burning team.","How to use","Use $c5_Taishi Ci$ and $c5_Lu Xun$ to inflict Burning on enemy's front row and back row, dealing damage to all enemies.|$c5_Taishi Ci$ can cooperate with $c5_Sun Quan$ to deal damage to enemy's front row while $c5_Lu Xun$ can cooperate with $c5_Gan Ning$ to deal damage to enemy's back row. $c5_Lu Meng$ can inflict Stun on targets who have Burning to control them.|Activate two Combo Skills: $c5_Taishi Ci + Sun Quan, Gan Ning + Lu Meng$ to further increase the damage.|$c5_Taishi Ci and Lu Xun$'s all-sided Burning can give full play to $c5_Lu Meng$'s Stun ability.","Warrior Analysis","Position 1: $c5_Taishi Ci$ uses skill to inflict Burning on enemy's front row.|Position 2: $c5_Lu Xun$ uses skill to inflict Burning on enemy's back row. (Position 1 and 2 can be switched)|Position 3: $c5_Lu Meng$ deals damage to all enemies and inflicts Stun.|Position 4: $c5_Sun Quan$ uses skill to deal damage to enemy's front row. A damage bonus is granted if the targets have Burning.|Position 5: $c5_Gan Ning$ uses skill to deal huge damage to enemy's back row and to launch Pursuit. A damage bonus is granted if the targets have Burning.|Position 6: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage. (Position 3, 4 and 5 can be switched)",},
        [6] = {6,"Front Row DPS Lineup","Faction Feature","Wu is good at $c5_inflicting Burning$, and their warriors enjoy ATK bonuses and control chance bonuses when they attack targets who are Burning.|Arson warriors are the core of the team. Inflict Burning on enemies and deal burst damage to them.|Carry out a series of attacks with arson warriors as the core to make good use of the advantage of Burning team.","How to use","Use $c5_Taishi Ci$ to inflict Burning on enemy's front row, and then deal huge damage to them and control them.|$c5_Sun Shangxiang and Sun Quan$ deals higher damage with higher Crit to targets who have Burning; $c5_Xiao Qiao$ inflicts Paralysis on targets who have Burning. Together they can control enemies and deal damage to them at the same time.|Activate the Combo Skill: $c5_Taishi Ci + Sun Quan$. $c5_Da Qiao$ can improve the team's survivability while $c5_Xiao Qiao$ can provide considerable damage bonuses.","Warrior Analysis","Position 1: $c5_Taishi Ci$ uses skill to inflict Burning on enemy's front row.|Position 2: $c5_Sun Shangxiang$ uses skill to deal huge damage to one enemy in the front row. A damage bonus is granted if the target has Burning.|Position 3: $c5_Sun Quan$ uses skill to deal damage to enemy's front row. A damage bonus is granted if the targets have Burning. (Position 2 and 3 can be switched)|Position 4: $c5_Da Qiao$'s skill and basic attack can inflict healing over time to improve the team's survivability.|Position 5: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage. (Position 4 and 5 can be switched)|Position 6: $c5_Xiao Qiao$ uses skill to inflict Paralysis on those who have Burning and to inflict damage bonus on allies.",},
        [7] = {7,"Poison DMG Lineup","Faction Feature","Han has powerful $c5_control abilities$, Anger decreasing abilities and Poison DMG abilities.|Control abilities can delay enemies' actions to a large extent; Anger decreasing abilities can delay enemies' use of skills; Poison DMG is powerful in the long term.|The strategies and lineups of control teams are various. They mostly win the game by weakening and consuming enemies.","How to use","The state Poisoned inflicted by $c5_Jia Xu and Yu Ji$'s skills deals high damage, and it lasts 2 rounds. The longer the battle, the higher the damage.|$c5_Zhang Jiao, Gongsun Zan and Yuan Shao$ can control enemies to prolong the battle and give full play to the effect of Poisoned.|After control and damage are guaranteed, activate two Combo Skills: $c5_Zhang Jiao + Yu Ji, Jia Xu + Gongsun Zan$ to further increase the damage.","Warrior Analysis","Position 1: $c5_Zhang Jiao$ uses skill to inflict Silence on enemy's front row, banning them from using skill on the first round.|Position 2: $c5_Gongsun Zan$ uses skill to inflict Decrease Anger on enemy's back row, banning them from using skill on the first round. (Position 1 and 2 can be switched)|Position 3: $c5_Jia Xu$ uses skill to inflict Poisoned on enemy's front row, dealing Poison DMG to them for 2 rounds.|Position 4: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage.|Position 5: $c5_Yu Ji$ uses skill to inflict Poisoned on 3 random enemies, dealing Poison DMG to them for 2 rounds. (Position 3, 4 and 5 can be switched)|Position 6: $c5_Yuan Shao$ uses skill to inflict Paralysis, banning enemies from using basic attack on the next round (unable to restore Anger), which can delay enemies' use of skills and prolong the battle.",},
        [8] = {8,"DPS Control Lineup","Faction Feature","Han has powerful $c5_control abilities$, Anger decreasing abilities and Poison DMG abilities.|Control abilities can delay enemies' actions to a large extent; Anger decreasing abilities can delay enemies' use of skills; Poison DMG is powerful in the long term.|The strategies and lineups of control teams are various. They mostly win the game by weakening and consuming enemies.","How to use","$c5_Yu Ji and Hua Xiong$ has considerable damage, $c5_Dong Zhuo$ has high survivability while $c5_Zhang Jiao$ has control abilities. They are suitable for both instances and PvP.|$c5_Hua Tuo$'s powerful healing can improve the team's survivability significantly.|After damage is guaranteed, activate two Combo Skills: $c5_Zhang Jiao + Yu Ji, Dong Zhuo + Hua Xiong$ to further increase the damage.","Warrior Analysis","Position 1: $c5_Zhang Jiao$ uses skill to inflict Silence on enemy's front row, banning them from using skill on the first round.|Position 2: $c5_Dong Zhuo$ uses skill to inflict a shield that can absorb huge damage for the team.|Position 3: $c5_Yu Ji$ uses skill to inflict Poisoned on 3 random enemies, dealing Poison DMG to them for 2 rounds.|Position 4: $c5_Hua Tuo$'s powerful healing can improve the team's survivability.|Position 5: $c5_Protagonist$ has considerable damage and HP, making it a tank that can deal damage. (Position 4 and 5 can be switched)|Position 6: $c5_Hua Xiong$ can deal huge damage to enemy's middle row and launch the last hit. (Position 3 and 6 can be switched)",},
    }
}

return team_recommend