

local VipConst = {}

VipConst.TAB_TYPE = {
	VIP_GIFT = 1,
	DISCOUNT_GIFT = 2,
	LUXURY_GIFT = 3,
	MONTH_CARD = 4,
	FOUNDATION = 5,
	FOUNDATION_APPSTORE = 6,
	JADE_BUY = 7,
	MAX = 8
}

VipConst.SUB_TAB_TYPE = {
	LEVEL_GIFT = 1,--等级礼包类型
	EXCHANGE = 2,--兑换类型
	LIMIT_SHOP = 3,
	LIMIT_WEEK_SHOP = 4,
	NORMAL_SHOP = 5,
	MAX = 6
}




VipConst.VIP_ADD_EXP_TYPE_CLICK_POSTER_GIRL = 1--i18n ui4
VipConst.VIP_ADD_EXP_TYPE_SELECT_REWARD = 3--i18n ui4
VipConst.VIP_ADD_EXP_CONDITION_ONLINE = 101--i18n ui4

return readOnly(VipConst)
