return {
    ["waves"] = {
        [1] = {
            ["rounds"] = {
                [1] = {
                    ["wave_index"] = 1,
                    ["attacks"] = {
                        [1] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["is_live"] = false,
                                    ["value"] = 21662,
                                    ["type"] = 1,
                                    ["actual_value"] = 281,
                                    ["defense_member"] = {
                                        ["member_info"] = 6015,
                                        ["order_pos"] = 131073,
                                    },
                                    ["protect"] = 0,
                                },
                                [2] = {
                                    ["is_live"] = false,
                                    ["value"] = 22397,
                                    ["type"] = 1,
                                    ["actual_value"] = 1730,
                                    ["defense_member"] = {
                                        ["member_info"] = 6011,
                                        ["order_pos"] = 131074,
                                    },
                                    ["protect"] = 0,
                                },
                                [3] = {
                                    ["defense_member"] = {
                                        ["member_info"] = 6015,
                                        ["order_pos"] = 131075,
                                    },
                                    ["actual_value"] = 1131,
                                    ["value"] = 27365,
                                    ["type"] = 1,
                                    ["is_live"] = false,
                                    ["hurt_infos"] = {
                                        [1] = {
                                            ["value"] = 0,
                                            ["id"] = 2,
                                        },
                                    },
                                    ["protect"] = 0,
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 103,
                                        ["order_pos"] = 65537,
                                    },
                                    ["value"] = 2,
                                    ["type"] = 2,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2101,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 103,
                                ["order_pos"] = 65537,
                            },
                            ["attack_hero_info"] = 65639,
                            ["skill_id"] = 1030010,
                        },
                        [2] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["is_live"] = true,
                                    ["value"] = 1,
                                    ["type"] = 1,
                                    ["actual_value"] = 1,
                                    ["defense_member"] = {
                                        ["member_info"] = 116,
                                        ["order_pos"] = 65538,
                                    },
                                    ["protect"] = 0,
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 129,
                                        ["order_pos"] = 131077,
                                    },
                                    ["value"] = 2,
                                    ["type"] = 2,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2101,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 129,
                                ["order_pos"] = 131077,
                            },
                            ["attack_hero_info"] = 131201,
                            ["skill_id"] = 1290010,
                        },
                        [3] = {
                            ["attack_infos"] = {
                                [1] = {
                                    ["is_live"] = false,
                                    ["value"] = 44204,
                                    ["type"] = 1,
                                    ["actual_value"] = 1849,
                                    ["defense_member"] = {
                                        ["member_info"] = 129,
                                        ["order_pos"] = 131077,
                                    },
                                    ["protect"] = 0,
                                },
                            },
                            ["angers"] = {
                                [1] = {
                                    ["member"] = {
                                        ["member_info"] = 116,
                                        ["order_pos"] = 65538,
                                    },
                                    ["value"] = 2,
                                    ["type"] = 2,
                                    ["stype_and_show_type"] = 999,
                                    ["buff_id"] = 2101,
                                },
                            },
                            ["is_live"] = true,
                            ["type"] = 0,
                            ["attack_pos"] = {
                                ["member_info"] = 116,
                                ["order_pos"] = 65538,
                            },
                            ["attack_hero_info"] = 65652,
                            ["skill_id"] = 1160010,
                        },
                    },
                    ["round_index"] = 1,
                },
            },
            ["members"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 116,
                    ["max_hp"] = 139343,
                    ["instrument_rank"] = 0,
                    ["hp"] = 139343,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 2,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 207,
                    ["max_hp"] = 160536,
                    ["instrument_rank"] = 0,
                    ["hp"] = 160536,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 4,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 208,
                    ["max_hp"] = 56496,
                    ["instrument_rank"] = 0,
                    ["hp"] = 56496,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 6,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 576097,
                    ["instrument_rank"] = 0,
                    ["hp"] = 576097,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 10,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["pos"] = 5,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 206,
                    ["max_hp"] = 121360,
                    ["instrument_rank"] = 0,
                    ["hp"] = 121360,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 4,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 3,
                },
                [6] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 103,
                    ["max_hp"] = 215978,
                    ["instrument_rank"] = 0,
                    ["hp"] = 215978,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 1,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 1,
                },
                [7] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6015,
                    ["max_hp"] = 281,
                    ["instrument_rank"] = 0,
                    ["hp"] = 281,
                    ["camp"] = 2,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 11003011,
                    ["anger"] = 2,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 1,
                },
                [8] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6011,
                    ["max_hp"] = 1730,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1730,
                    ["camp"] = 2,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 11003012,
                    ["anger"] = 2,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 2,
                },
                [9] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 6015,
                    ["max_hp"] = 1131,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1131,
                    ["camp"] = 2,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 11003013,
                    ["anger"] = 2,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 3,
                },
                [10] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 129,
                    ["max_hp"] = 1849,
                    ["instrument_rank"] = 0,
                    ["hp"] = 1849,
                    ["camp"] = 2,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 11003015,
                    ["anger"] = 2,
                    ["is_user"] = false,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 5,
                },
            },
            ["pets"] = {
            },
            ["init_buff"] = {
            },
            ["first_order"] = 1,
            ["members_final"] = {
                [1] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 1,
                    ["max_hp"] = 576097,
                    ["instrument_rank"] = 0,
                    ["hp"] = 576097,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 10,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = true,
                    ["pos"] = 5,
                },
                [2] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 206,
                    ["max_hp"] = 121360,
                    ["instrument_rank"] = 0,
                    ["hp"] = 121360,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 4,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 3,
                },
                [3] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 103,
                    ["max_hp"] = 215978,
                    ["instrument_rank"] = 0,
                    ["hp"] = 215978,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 1,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 1,
                },
                [4] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 116,
                    ["max_hp"] = 139343,
                    ["instrument_rank"] = 0,
                    ["hp"] = 139342,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 4,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 2,
                },
                [5] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 207,
                    ["max_hp"] = 160536,
                    ["instrument_rank"] = 0,
                    ["hp"] = 160536,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 4,
                },
                [6] = {
                    ["limit_lv"] = 0,
                    ["knight_id"] = 208,
                    ["max_hp"] = 56496,
                    ["instrument_rank"] = 0,
                    ["hp"] = 56496,
                    ["camp"] = 1,
                    ["protect"] = 0,
                    ["rtg_lv"] = 0,
                    ["rank_lv"] = 0,
                    ["monster_id"] = 0,
                    ["anger"] = 2,
                    ["is_user"] = true,
                    ["instrument_id"] = 0,
                    ["is_leader"] = false,
                    ["pos"] = 6,
                },
            },
        },
    },
    ["defense_power"] = 0,
    ["version"] = 1,
    ["attack_power"] = 2207500,
    ["is_win"] = true,
    ["first_order"] = 1,
    ["defense_officer_level"] = 0,
    ["defense_name"] = "",
    ["pk_type"] = 1,
    ["max_round_num"] = 10,
    ["skill_ids"] = {
        [1] = 1030010,
        [2] = 1290010,
        [3] = 1160010,
    },
    ["attack_base_id"] = 1,
    ["attack_officer_level"] = 0,
    ["attack_name"] = "yyq",
    ["attack_hurt"] = 115628,
    ["defense_base_id"] = 0,
}
