--team_recommend

local team_recommend = {
    -- key
    __key_map = {
      id = 1,    --阵容推荐ID_key-int 
      name = 2,    --阵容名称-越南语-string 
      title1 = 3,    --说明标题1-越南语-string 
      description1 = 4,    --说明内容1-越南语-string 
      title2 = 5,    --说明标题2-越南语-string 
      description2 = 6,    --说明内容2-越南语-string 
      title3 = 7,    --说明标题3-越南语-string 
      description3 = 8,    --说明内容3-越南语-string 
    
    },
    -- data
    _data = {
        [1] = {1,"Sát Thương Trận","Đặc Sắc","Ngụy có $c5_khả năng hồi nộ mạnh$, tất cả Tướng đều có thiên phú hồi nộ, có thể kết hợp tổ thành cách chơi $c5_Động Cơ Bất Tử$|Động Cơ Bất Tử tức là mỗi lượt giúp Tướng chỉ định hồi phục đủ lượng nộ khí, giúp Tướng mỗi lần ra tay đều có thể thi triển được kỹ năng|Cách chơi Động Cơ Bất Tử rất đa dạng và linh hoạt, có thể dựa trên Tướng đang có và nhu cầu cá nhân để tạo ra trận hình Động Cơ Bất Tử của riêng mình.","Cách Đánh","$c5_Điển Vi$ sát thương bạo kích cao, $c5_Hứa Chử$ tiêu diệt kẻ địch sinh lực thấp, $c5_Trương Liêu$ đột kích hàng sau|$c5_Trương Hợp$ kỹ năng kèm Vô Địch Thuẫn có khả năng bảo vệ đồng đội mạnh, $c5_Tuân Úc$ trị liệu hiệu quả và trị liệu khi bị tấn công đảm bảo khả năng sống sót của đồng đội|Đã kích hoạt hai nhóm hợp kích $c5_Điển Vi+Hứa Chử$, $c5_Trương Liêu+Trương Hợp$, sát thương tăng mạnh","Phân tích Tướng","Vị trí 1 $c5_Điển Vi$, sát thương bạo kích cao, có thể đánh trọng thương hoặc diệt nhanh kẻ địch ở vị trí hàng dọc|Vị trí 2 $c5_Trương Hợp$, thi triển kỹ năng tấn công đơn vị Tướng địch hàng sau và vô địch bảo vệ đồng đội sinh lực thấp nhất, có khả năng bảo vệ mạnh|Vị trí 3 $c5_Hứa Chử$, thi triển kỹ năng tấn công địch hàng trước kèm Truy Kích chắc chắn bạo, khả năng tiêu diệt kẻ địch sinh lực thấp mạnh|Vị trí 4 $c5_Trương Liêu$, thi triển kỹ năng tấn công địch hàng sau, có thể kết hợp với Điển Vi, Trương Hợp gây đả kích chí mạng cho Tướng địch hàng sau|Vị trí 5 $c5_Tuân Úc$, trị liệu hiệu quả cực cao, khả năng hồi sinh lực khi bị tấn công đảm bảo khả năng sống sót của đội|Vị trí 6 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được (Tất cả vị trí đều có thể hoán đổi)",},
        [2] = {2,"Khống Chế-ST","Đặc Sắc","Ngụy có $c5_khả năng hồi nộ mạnh$, tất cả Tướng đều có thiên phú hồi nộ, có thể kết hợp tổ thành cách chơi $c5_Động Cơ Bất Tử$|Động Cơ Bất Tử tức là mỗi lượt giúp Tướng chỉ định hồi phục đủ lượng nộ khí, giúp Tướng mỗi lần ra tay đều có thể thi triển được kỹ năng|Cách chơi Động Cơ Bất Tử rất đa dạng và linh hoạt, có thể dựa trên Tướng đang có và nhu cầu cá nhân để tạo ra trận hình Động Cơ Bất Tử của riêng mình.","Cách Đánh","Trầm mặc, choáng, vô địch, hồi sinh lực, khống chế đa dạng kèm hồi phục, kẻ địch nằm gọn trong tay ta.|$c5_Quách Gia$ trầm mặc địch hàng trước, $c5_Tào Nhân$ choáng địch hàng dọc, $c5_Hạ Hầu Đôn$ kiên cường phản thương và có khả năng hồi sinh lực, $c5_Trương Hợp$ vô địch bảo vệ, $c5_Tuân Úc$ trị liệu hiệu quả cao|Đã kích hoạt hợp kích $c5_Hạ Hầu Đôn+Tào Nhân$, Trận Hình thông qua khống chế và bảo vệ, giảm sát thương phe ta, tiêu diệt kẻ địch","Phân tích Tướng","Vị trí 1 $c5_Quách Gia$, thi triển kỹ năng trầm mặc địch hàng trước, có thể hạn chế địch hàng trước thi triển kỹ năng ở lượt đầu|Vị trí 2 $c5_Tào Nhân$, thi triển kỹ năng choáng địch hàng dọc, có thể hạn chế địch hàng dọc thi triển kỹ năng ở lượt đầu|Vị trí 3 $c5_Hạ Hầu Đôn$, thi triển kỹ năng tấn công địch hàng dọc, hồi phục sinh lực bản thân, có khả năng phản thương mạnh, có thể khắc chế phe địch một mình diệt Tướng (Vị trí 2, 3 có thể hoán đổi)|Vị trí 4 $c5_Tuân Úc$, trị liệu hiệu quả cực cao, khả năng hồi sinh lực khi bị tấn công đảm bảo khả năng sống sót của đội|Vị trí 5 $c5_Trương Hợp$, thi triển kỹ năng tấn công đơn vị Tướng địch hàng sau, vô địch bảo vệ đồng đội sinh lực thấp nhất, có khả năng bảo vệ cao|Vị trí 6 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được (Tất cả vị trí đều có thể hoán đổi)",},
        [3] = {3,"Sát Thương-Bạo","Đặc Sắc","Thục có $c5_khả năng sát thương lớn$, thông qua sát thương bạo kích nhanh chóng diệt kẻ địch|Áp dụng chiến thuật một đòn tất thắng để tốc chiến tốc thắng; hoặc khống chế kẻ địch, tiêu diệt dần dần? Chiến thuật đa dạng với nhiều tổ hợp|Tổ hợp khác nhau sẽ có hiệu quả khác nhau, mục đích đều nhằm tạo ra sát thương cao nhất, tận hưởng cảm giác diệt nhanh","Cách Đánh","$c5_Mã Siêu$ Tiên Thủ cung cấp hộ thuẫn giảm sát thương cho hàng trước; $c5_Lưu Bị$ trị liệu mạnh và khi bị sát thương kỹ năng giúp hồi sinh lực toàn đội, đảm bảo khả năng sống sót của đội|$c5_Trương Phi, Quan Vũ, Hoàng Trung$ có sát thương mạnh, nhanh chóng tiêu diệt kẻ địch, kết thúc cuộc chiến|Đã kích hoạt hai nhóm hợp kích $c5_Mã Siêu+Hoàng Trung$, $c5_Quan Vũ+Trương Phi$, sát thương bạo kích mạnh hơn","Phân tích Tướng","Vị trí 1 $c5_Mã Siêu$, sau khi thi triển kỹ năng giúp hàng trước phe ta cung cấp Hộ Thuẫn Giảm Thương, tăng khả năng sống sót của đội|Vị trí 2 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được|Vị trí 3 $c5_Lưu Bị$, khả năng trị liệu mạnh và khi bị sát thương kỹ năng giúp hồi sinh lực toàn đội, đảm bảo khả năng sống sót của đội|Vị trí 4 $c5_Trương Phi$, thi triển kỹ năng tấn công địch hàng trước, sinh lực càng thấp sát thương càng cao, khả năng sát thương mạnh|Vị trí 5$c5_Hoàng Trung$, thi triển kỹ năng tấn công địch hàng trước, tiêu diệt nhanh kẻ địch sinh lực thấp|Vị trí 6 $c5_Quan Vũ$, gây sát thương đơn vị hàng trước mạnh, tỉ lệ bạo kích cao, thích hợp một mình diệt nhanh Tướng chính của địch hàng trước(Vị trí 2, 3, 4, 5, 6 có thể hoán đổi)",},
        [4] = {4,"Khống Chế-ST","Đặc Sắc","Thục có $c5_khả năng sát thương lớn$, thông qua sát thương bạo kích nhanh chóng diệt kẻ địch|Áp dụng chiến thuật một đòn tất thắng để tốc chiến tốc thắng; hoặc khống chế kẻ địch, tiêu diệt dần dần? Chiến thuật đa dạng với nhiều tổ hợp|Tổ hợp khác nhau sẽ có hiệu quả khác nhau, mục đích đều nhằm tạo ra sát thương cao nhất, tận hưởng cảm giác diệt nhanh","Cách Đánh","Ngoài việc đảm bảo khả năng sát thương còn tăng khả năng khống chế phe địch của $c5_Từ Thứ$ và khả năng tăng tấn công của Bàng Thống|$c5_Trương Phi, Quan Vũ$ sát thương mạnh, $c5_Bàng Thống$ tăng hiệu quả tấn công cho toàn đội, sát thương thêm bạo kích|Đã kích hoạt hai nhóm hợp kích $c5_Bàng Thống+Từ Thứ, Quan Vũ+Trương Phi$, sát thương đội mạnh hơn","Phân tích Tướng","Vị trí 1 $c5_Quan Vũ$, gây sát thương đơn vị hàng trước mạnh, tỉ lệ bạo kích cao, thích hợp một mình diệt nhanh Tướng chính của địch hàng trước, giành lấy ưu thế|Vị trí 2 $c5_Từ Thứ$, thi triển kỹ năng kèm hiệu quả choáng, khống chế tốt Tướng địch hàng sau, gián đoạn kỹ năng thi triển của mục tiêu, trì hoãn sát thương phe địch|Vị trí 3 $c5_Lưu Bị$, khả năng trị liệu mạnh và khi bị sát thương kỹ năng giúp hồi sinh lực toàn đội, đảm bảo khả năng sống sót của đội|Vị trí 4 $c5_Bàng Thống$, có nhiều vòng sáng tăng sát thương, tăn tối đa sát thương của Tướng|Vị trí 5 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được|Vị trí 6 $c5_Trương Phi$, thi triển kỹ năng tấn công địch hàng trước, sinh lực càng thấp sát thương càng cao, khả năng sát thương mạnh (Tất cả vị trí đều có thể hoán đổi)",},
        [5] = {5,"Khống Chế-ST","Đặc Sắc","Ngô có $c5_khả năng hỏa công mạnh$, với mục tiêu bị thiêu đốt có thể tăng tấn công và tăng tỉ lệ khống chế|Tướng hỏa công là nòng cốt của đội, thiêu đốt kẻ địch, sau đó gây sát thương bạo phát|Xoay quanh khả năng Tướng hỏa công có thể kết hợp thành nhiều tổ  hợp, phát huy tối đa ưu thế thiêu đốt","Cách Đánh","Kết hợp $c5_Thái Sử Từ$ hỏa công hàng trước, $c5_Lục Tốn$ hỏa công hàng sau, đả kích toàn diện phe địch|$c5_Thái Sử Từ$ kết hợp $c5_Tôn Quyền$, gây sát thương địch hàng trước, $c5_Lục Tốn$ kết hợp $c5_Cam Ninh$, gây sát thương địch hàng sau, $c5_Lữ Mông$ khiến mục tiêu thiêu đốt có xác suất kèm hiệu quả choáng, đạt đến mục đích khống chế mục tiêu|Kích hoạt hai nhóm hợp kích $c5_Thái Sử Từ+Tôn Quyền, Cam Ninh+Lữ Mông$, sát thương mạnh hơn|$c5_Thái Sử Từ, Lục Tốn$ toàn diện thiêu đốt phát huy tối đa kỹ năng $c5_Lữ Mông$ tấn công toàn thể phe địch kèm hiệu quả choáng.","Phân tích Tướng","Vị trí 1 $c5_Thái Sử Từ$, thi triển kỹ năng gây hiệu quả thiêu đốt cho địch hàng trước|Vị trí 2 $c5_Lục Tốn$, thi triển kỹ năng gây hiệu quả thiêu đốt cho địch hàng sau(Vị trí 1, 2 có thể hoán đổi)|Vị trí 3 $c5_Lữ Mông$, gây sát thương toàn thể phe địch, kèm hiệu quả choáng, hống chế phe địch|Vị trí 4 $c5_Tôn Quyền$, thi triển kỹ năng gây sát thương cho địch hàng trước, có tăng ST với mục tiêu bị thiêu đốt|Vị trí 5 $c5_Cam Ninh$, thi triển kỹ năng gây nhiều sát thương cho 1 kẻ địch hàng sau, kèm truy kích, có tăng ST với mục tiêu bị thiêu đốt, có khả năng diệt nhanh địch hàng sau|Vị trí 6 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được (Vị trí 3, 4, 5 có thể hoán đổi)",},
        [6] = {6,"Sát Thương-Trước","Đặc Sắc","Ngô có $c5_khả năng hỏa công mạnh$, với mục tiêu bị thiêu đốt có thể tăng tấn công và tăng tỉ lệ khống chế|Tướng hỏa công là nòng cốt của đội, thiêu đốt kẻ địch, sau đó gây sát thương bạo phát|Xoay quanh khả năng Tướng hỏa công có thể kết hợp thành nhiều tổ  hợp, phát huy tối đa ưu thế thiêu đốt","Cách Đánh","Kết hợp khả năng hỏa công hàng trước của $c5_Thái Sử Từ$, gây sát thương và khống chế địch hàng trước|$c5_Thượng Hương, Tôn Quyền$ gây sát thương cho mục tiêu bị thiêu đốt, bạo kích tăng, $c5_Tiểu Kiều$ khiến mục tiêu bị thiêu đốt kèm hiệu quả tê liệt, tổ hợp với nhau sẽ gây cho địch hàng trước một loạt sát thương và hiệu quả khống chế|Kích hoạt hợp kích $c5_Thái Sử Từ+Tôn Quyền$, $c5_Đại Kiều$ cung cấp khả năng sống sót cho đội, $c5_Tiểu Kiều$ tăng sát thương cho đội","Phân tích Tướng","Vị trí 1 $c5_Thái Sử Từ$, thi triển kỹ năng gây hiệu quả thiêu đốt cho địch hàng trước|Vị trí 2 $c5_Thượng Hương$, thi triển kỹ năng gây nhiều sát thương cho 1 kẻ địch hàng trước, có tăng ST với mục tiêu bị thiêu đốt|Vị trí 3$c5_Tôn Quyền$, thi triển kỹ năng gây sát thương cho địch hàng trước, có tăng ST với mục tiêu bị thiêu đốt (Vị trí 2, 3có thể hoán đổi)|Vị trí 4 $c5_Đại Kiều$, thi triển kỹ năng, đánh thường kèm hiệu quả trị liệu liên tục, tăng khả năng sống sót của đội|Vị trí 5 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được (Vị trí 4, 5 có thể hoán đổi)|Vị trí 6 $c5_Tiểu Kiều$, thi triển kỹ năng khiến mục tiêu thiêu đốt kèm hiệu quả tê liệt, cung cấp tăng ST cho đội",},
        [7] = {7,"Độc Thương Trận","Đặc Sắc","Quần Hùng có $c5_khả năng khống chế mạnh$, đồng thời có khả năng giảm nộ và sát thương độc|Khả năng khống chế tối đa kéo dài thời gian của kẻ địch; khả năng giảm nộ kéo dài thời gian thi triển kỹ năng của kẻ địch; khả năng duy trì sát thương trúng độc vô cùng nổi bật|Cách chơi đội khống chế đa dạng, linh hoạt, có thể áp dụng các tổ hợp khống chế khác nhau, giảm sức mạnh kẻ địch, giành chiến thắng","Cách Đánh","Kỹ năng kèm hiệu quả trúng độc của $c5_Giả Hủ, Vu Cát$ có sát thương cao, duy trì 2 lượt, số lượt chiến đấu càng lớn, sát thương càng cao|$c5_Trương Giác, Công Tôn Toản, Viên Thiệu$ khống chế đối thủ tối đa, kéo dài số lượt chiến đấu, phát huy hiệu quả tối đa của sát thương trúng độc|Đảm bảo sát thương, khống chế cùng lúc, đã kích hoạt hai nhóm hợp kích $c5_Trương Giác+Vu Cát, Giả Hủ+Công Tôn Toản$, sát thương mạnh hơn","Phân tích Tướng","Vị trí 1 $c5_Trương Giác$, thi triển kỹ năng kèm hiệu quả trầm mặc, có thể hạn chế địch hàng trước thi triển kỹ năng ở lượt đầu|Vị trí 2$c5_Công Tôn Toản$, thi triển kỹ năng kèm hiệu quả giảm nộ, có thể hạn chế địch hàng sau thi triển kỹ năng ở lượt đầu (Vị trí 1, 2 có thể hoán đổi)|Vị trí 3 $c5_Giả Hủ$, thi triển kỹ năng kèm hiệu quả trúng độc, có thể gây sát thương trúng độc 2 lượt cho địch hàng trước|Vị trí 4 $c5_Nhân vật$, sát thương cao, sinh lực cũng không tồi, đánh được chịu đòn được|Vị trí 5 $c5_Vu Cát$, thi triển kỹ năng kèm hiệu quả trúng độc, gây sát thương trúng độc 2 lượt cho 3 kẻ địch ngẫu nhiên (Vị trí 3, 4, 5 có thể hoán đổi)|Vị trí 6 $c5_Viên Thiệu$, thi triển kỹ năng kèm hiệu quả tê liệt, khiến phe địch trong 2 lượt không thể đánh thường (không thể hồi nộ), trì hoãn thi triển kỹ năng lượt kế của phe địch, đạt mục đích kéo dài số lượt chiến đấu",},
        [8] = {8,"Khống Chế-ST","Đặc Sắc","Quần Hùng có $c5_khả năng khống chế mạnh$, đồng thời có khả năng giảm nộ và sát thương độc|Khả năng khống chế tối đa kéo dài thời gian của kẻ địch; khả năng giảm nộ kéo dài thời gian thi triển kỹ năng của kẻ địch; khả năng duy trì sát thương trúng độc vô cùng nổi bật|Cách chơi đội khống chế đa dạng, linh hoạt, có thể áp dụng các tổ hợp khống chế khác nhau, giảm sức mạnh kẻ địch, giành chiến thắng","Cách Đánh","$c5_Vu Cát, Hoa Hùng$ có khả năng sát thương tốt, $c5_Đổng Trác$ có khả năng sinh tồn mạnh, $c5_Trương Giác$ có khả năng khống chế|$c5_Hoa Đà$ trị liệu giỏi, giúp tăng khả năng sống sót của đội|Đảm bảo sát thương, đã kích hoạt hai nhóm hợp kích $c5_Trương Giác+Vu Cát, Đổng Trác+Hoa Hùng$, sát thương mạnh hơn","Phân tích Tướng","Vị trí 1$c5_Trương Giác$, , thi triển kỹ năng kèm hiệu quả Trầm mặc, có thể hạn chế địch hàng trước thi triển kỹ năng ở lượt đầu|Vị trí 2$c5_Đổng Trác$, thi triển kỹ năng kèm Hộ Thuẫn giảm nhiều sát thương phải chịu|Vị trí 3$c5_Vu Cát$, thi triển kèm hiệu quả Trúng Độc, gây 2 lượt trúng độc với 3 kẻ địch ngẫu nhiên: Hiệu quả Trúng Độc|Vị trí 4$c5_Hoa Đà$, năng lực trị liệu giúp đội tăng khả năng sinh tồn|Vị trí 5$c5_Nhân vật $, sát thương mạnh, sinh lực cao, tấn công chống đỡ đều ổn (Có thể đổi giữa vị trí 4, 5)|Vị trí 6$c5_Hoa Hùng$, tướng tấn công mạnh, gây nhiều sát thương lên kẻ địch hàng ngang, có khả năng dứt điểm (Vị trí 3, 6 có thể đổi cho nhau)",},
    }
}

return team_recommend